<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>no.nav.dokdisteformidling</groupId>
	<artifactId>dokdisteformidling</artifactId>
	<packaging>pom</packaging>
	<version>1.0-SNAPSHOT</version>
	<modules>
		<module>app</module>
		<module>core</module>
		<module>qdist011</module>
		<module>qdist013</module>
		<module>sdist001</module>
		<module>schemas-avtaltmelding</module>
		<module>schemas-altinn</module>
	</modules>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.5.RELEASE</version>
	</parent>

	<properties>
		<java.version>11</java.version>
		<camel.version>3.6.0</camel.version>
		<javax.inject.version>1</javax.inject.version>
		<logstash-logback-encoder.version>6.5</logstash-logback-encoder.version>
		<jakarta.xml.ws-api.version>2.3.3</jakarta.xml.ws-api.version>
		<lombok.version>1.18.14</lombok.version>
		<resilience4j.version>1.6.1</resilience4j.version>
		<aws-java-sdk-s3.version>1.11.883</aws-java-sdk-s3.version>
		<dokkat.version>11.0.5</dokkat.version>
		<wmq.version>9.2.0.1</wmq.version>
		<cxf.version>3.4.1</cxf.version>
		<melding-virksomhet-dokdistfordeling.version>2.0.4</melding-virksomhet-dokdistfordeling.version>
		<nav-digitalKontaktinformasjon-v1-tjenestespesifikasjon>2.0.0</nav-digitalKontaktinformasjon-v1-tjenestespesifikasjon>
		<sdpkanal-tjenestespesifikasjon.version>1.1.0</sdpkanal-tjenestespesifikasjon.version>
		<jaxb2-basics-runtime.version>1.11.1</jaxb2-basics-runtime.version>
		<commons-lang3.version>3.11</commons-lang3.version>
		<commons-io.version>2.8.0</commons-io.version>
		<commons-asic.version>0.9.3</commons-asic.version>
		<nimbus-jose-jwt.version>9.0.1</nimbus-jose-jwt.version>
		<rxjava.version>2.2.20</rxjava.version>
		<jaxws-ri.version>3.0.0-M1</jaxws-ri.version>
		<!-- test -->
		<awaitility.version>4.0.3</awaitility.version>
		<activemq.version>5.16.0</activemq.version>
		<junit5.mockito.version>2.25.1</junit5.mockito.version>
		<sshd-sftp.version>2.0.0</sshd-sftp.version>
		<spring-cloud-contract-wiremock.version>2.2.4.RELEASE</spring-cloud-contract-wiremock.version>
		<!-- wiremock compat -->
		<xmlunit-core.version>2.6.3</xmlunit-core.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>no.nav.dokdisteformidling</groupId>
				<artifactId>core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokdisteformidling</groupId>
				<artifactId>qdist011</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokdisteformidling</groupId>
				<artifactId>qdist013</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokdisteformidling</groupId>
				<artifactId>sdist001</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokdisteformidling</groupId>
				<artifactId>schemas-avtaltmelding</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokdisteformidling</groupId>
				<artifactId>schemas-altinn</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokkat</groupId>
				<artifactId>dokkat-api</artifactId>
				<version>${dokkat.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.dokkat</groupId>
				<artifactId>dokkat-schemas</artifactId>
				<version>${dokkat.version}</version>
			</dependency>
			<dependency>
				<groupId>no.nav.meldinger.virksomhet</groupId>
				<artifactId>melding-virksomhet-dokdistfordeling</artifactId>
				<version>${melding-virksomhet-dokdistfordeling.version}</version>
			</dependency>

			<dependency>
				<groupId>no.nav.tjenester</groupId>
				<artifactId>nav-sdpkanal-tjenestespesifikasjon</artifactId>
				<version>${sdpkanal-tjenestespesifikasjon.version}</version>
				<classifier>jaxws</classifier>
			</dependency>
			<dependency>
				<groupId>javax.inject</groupId>
				<artifactId>javax.inject</artifactId>
				<version>${javax.inject.version}</version>
			</dependency>
			<dependency>
				<groupId>net.logstash.logback</groupId>
				<artifactId>logstash-logback-encoder</artifactId>
				<version>${logstash-logback-encoder.version}</version>
			</dependency>

			<dependency>
				<groupId>org.jvnet.jaxb2_commons</groupId>
				<artifactId>jaxb2-basics-runtime</artifactId>
				<version>${jaxb2-basics-runtime.version}</version>
			</dependency>
			<dependency>
				<groupId>com.amazonaws</groupId>
				<artifactId>aws-java-sdk-s3</artifactId>
				<version>${aws-java-sdk-s3.version}</version>
			</dependency>

			<dependency>
				<groupId>jakarta.xml.ws</groupId>
				<artifactId>jakarta.xml.ws-api</artifactId>
				<version>${jakarta.xml.ws-api.version}</version>
				<type>pom</type>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.ws</groupId>
				<artifactId>jaxws-ri</artifactId>
				<version>${jaxws-ri.version}</version>
				<type>pom</type>
			</dependency>
			<dependency>
				<groupId>io.reactivex.rxjava2</groupId>
				<artifactId>rxjava</artifactId>
				<version>${rxjava.version}</version>
			</dependency>

			<dependency>
				<groupId>com.ibm.mq</groupId>
				<artifactId>com.ibm.mq.allclient</artifactId>
				<version>${wmq.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.camel.springboot</groupId>
				<artifactId>camel-spring-boot-bom</artifactId>
				<version>${camel.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>${commons-lang3.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-spring-boot-starter-jaxws</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-ws-security</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-frontend-jaxws</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-transports-http</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-core</artifactId>
				<scope>compile</scope>
				<version>${cxf.version}</version>
			</dependency>


			<dependency>
				<groupId>no.difi.commons</groupId>
				<artifactId>commons-asic</artifactId>
				<version>${commons-asic.version}</version>
			</dependency>
			<dependency>
				<groupId>commons-io</groupId>
				<artifactId>commons-io</artifactId>
				<version>${commons-io.version}</version>
			</dependency>
			<dependency>
				<groupId>com.nimbusds</groupId>
				<artifactId>nimbus-jose-jwt</artifactId>
				<version>${nimbus-jose-jwt.version}</version>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
			</dependency>

			<!--Tjenestegrensesnitt-->
			<dependency>
				<groupId>no.nav.tjenester.fim</groupId>
				<artifactId>nav-digitalKontaktinformasjon-v1-tjenestespesifikasjon</artifactId>
				<version>${nav-digitalKontaktinformasjon-v1-tjenestespesifikasjon}</version>
				<classifier>jaxws</classifier>
			</dependency>

			<!--Selftest metrics-->
			<dependency>
				<groupId>io.github.resilience4j</groupId>
				<artifactId>resilience4j-prometheus</artifactId>
				<version>${resilience4j.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.resilience4j</groupId>
				<artifactId>resilience4j-timelimiter</artifactId>
				<version>${resilience4j.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.resilience4j</groupId>
				<artifactId>resilience4j-circuitbreaker</artifactId>
				<version>${resilience4j.version}</version>
			</dependency>
			<!-- test -->
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-junit-jupiter</artifactId>
				<version>${junit5.mockito.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-contract-wiremock</artifactId>
				<version>${spring-cloud-contract-wiremock.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.sshd</groupId>
				<artifactId>sshd-sftp</artifactId>
				<version>${sshd-sftp.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.activemq</groupId>
				<artifactId>activemq-broker</artifactId>
				<version>${activemq.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.awaitility</groupId>
				<artifactId>awaitility</artifactId>
				<version>${awaitility.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.xmlunit</groupId>
				<artifactId>xmlunit-assertj</artifactId>
				<version>${xmlunit-core.version}</version>
				<scope>test</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-webdav-jackrabbit</artifactId>
				<version>1.0</version>
			</extension>
		</extensions>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-toolchains-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<goals>
							<goal>toolchain</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<toolchains>
						<jdk>
							<version>11</version>
							<vendor>openjdk</vendor>
						</jdk>
					</toolchains>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M4</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-failsafe-plugin</artifactId>
				<version>3.0.0-M4</version>
			</plugin>
		</plugins>
	</build>
</project>