//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.12 at 03:14:19 PM CET 
//


package no.nav.dokdisteformidling.consumer.eformidling.dokumentpakker.brokerservicemanifest;

import com.kscs.util.jaxb.Buildable;
import com.kscs.util.jaxb.PropertyTree;
import com.kscs.util.jaxb.PropertyTreeUse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * This type is the manifest root element. The container of all the file meta-data.
 *
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExternalServiceCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ExternalServiceEditionCode" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="SendersReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Reportee" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="FileList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="File" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="CheckSum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PropertyList" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Property" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="PropertyKey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="PropertyValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "externalServiceCode",
        "externalServiceEditionCode",
        "sendersReference",
        "reportee",
        "sentDate",
        "fileList",
        "propertyList"
})
@XmlRootElement(name = "BrokerServiceManifest")
public class BrokerServiceManifest {

    @XmlElement(name = "ExternalServiceCode", required = true)
    protected String externalServiceCode;
    @XmlElement(name = "ExternalServiceEditionCode", required = true)
    protected BigInteger externalServiceEditionCode;
    @XmlElement(name = "SendersReference", required = true)
    protected String sendersReference;
    @XmlElement(name = "Reportee", required = true)
    protected String reportee;
    @XmlElement(name = "SentDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sentDate;
    @XmlElement(name = "FileList")
    protected BrokerServiceManifest.FileList fileList;
    @XmlElement(name = "PropertyList")
    protected BrokerServiceManifest.PropertyList propertyList;

    /**
     * Gets the value of the externalServiceCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExternalServiceCode() {
        return externalServiceCode;
    }

    /**
     * Sets the value of the externalServiceCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExternalServiceCode(String value) {
        this.externalServiceCode = value;
    }

    /**
     * Gets the value of the externalServiceEditionCode property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getExternalServiceEditionCode() {
        return externalServiceEditionCode;
    }

    /**
     * Sets the value of the externalServiceEditionCode property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setExternalServiceEditionCode(BigInteger value) {
        this.externalServiceEditionCode = value;
    }

    /**
     * Gets the value of the sendersReference property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSendersReference() {
        return sendersReference;
    }

    /**
     * Sets the value of the sendersReference property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSendersReference(String value) {
        this.sendersReference = value;
    }

    /**
     * Gets the value of the reportee property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReportee() {
        return reportee;
    }

    /**
     * Sets the value of the reportee property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReportee(String value) {
        this.reportee = value;
    }

    /**
     * Gets the value of the sentDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getSentDate() {
        return sentDate;
    }

    /**
     * Sets the value of the sentDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setSentDate(XMLGregorianCalendar value) {
        this.sentDate = value;
    }

    /**
     * Gets the value of the fileList property.
     *
     * @return
     *     possible object is
     *     {@link BrokerServiceManifest.FileList }
     *
     */
    public BrokerServiceManifest.FileList getFileList() {
        return fileList;
    }

    /**
     * Sets the value of the fileList property.
     *
     * @param value
     *     allowed object is
     *     {@link BrokerServiceManifest.FileList }
     *
     */
    public void setFileList(BrokerServiceManifest.FileList value) {
        this.fileList = value;
    }

    /**
     * Gets the value of the propertyList property.
     *
     * @return
     *     possible object is
     *     {@link BrokerServiceManifest.PropertyList }
     *
     */
    public BrokerServiceManifest.PropertyList getPropertyList() {
        return propertyList;
    }

    /**
     * Sets the value of the propertyList property.
     *
     * @param value
     *     allowed object is
     *     {@link BrokerServiceManifest.PropertyList }
     *
     */
    public void setPropertyList(BrokerServiceManifest.PropertyList value) {
        this.propertyList = value;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     *
     * @param _other A builder instance to which the state of this object will be copied.
     */
    public <_B> void copyTo(final BrokerServiceManifest.Builder<_B> _other) {
        _other.externalServiceCode = this.externalServiceCode;
        _other.externalServiceEditionCode = this.externalServiceEditionCode;
        _other.sendersReference = this.sendersReference;
        _other.reportee = this.reportee;
        _other.sentDate = ((this.sentDate == null) ? null : ((XMLGregorianCalendar) this.sentDate.clone()));
        _other.fileList = ((this.fileList == null) ? null : this.fileList.newCopyBuilder(_other));
        _other.propertyList = ((this.propertyList == null) ? null : this.propertyList.newCopyBuilder(_other));
    }

    public <_B> BrokerServiceManifest.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
        return new BrokerServiceManifest.Builder<_B>(_parentBuilder, this, true);
    }

    public BrokerServiceManifest.Builder<Void> newCopyBuilder() {
        return newCopyBuilder(null);
    }

    public static BrokerServiceManifest.Builder<Void> builder() {
        return new BrokerServiceManifest.Builder<Void>(null, null, false);
    }

    public static <_B> BrokerServiceManifest.Builder<_B> copyOf(final BrokerServiceManifest _other) {
        final BrokerServiceManifest.Builder<_B> _newBuilder = new BrokerServiceManifest.Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder);
        return _newBuilder;
    }

    /**
     * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
     *
     * @param _other A builder instance to which the state of this object will be copied.
     */
    public <_B> void copyTo(final BrokerServiceManifest.Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final PropertyTree externalServiceCodePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("externalServiceCode"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (externalServiceCodePropertyTree != null) : ((externalServiceCodePropertyTree == null) || (!externalServiceCodePropertyTree.isLeaf())))) {
            _other.externalServiceCode = this.externalServiceCode;
        }
        final PropertyTree externalServiceEditionCodePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("externalServiceEditionCode"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (externalServiceEditionCodePropertyTree != null) : ((externalServiceEditionCodePropertyTree == null) || (!externalServiceEditionCodePropertyTree.isLeaf())))) {
            _other.externalServiceEditionCode = this.externalServiceEditionCode;
        }
        final PropertyTree sendersReferencePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("sendersReference"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (sendersReferencePropertyTree != null) : ((sendersReferencePropertyTree == null) || (!sendersReferencePropertyTree.isLeaf())))) {
            _other.sendersReference = this.sendersReference;
        }
        final PropertyTree reporteePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("reportee"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (reporteePropertyTree != null) : ((reporteePropertyTree == null) || (!reporteePropertyTree.isLeaf())))) {
            _other.reportee = this.reportee;
        }
        final PropertyTree sentDatePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("sentDate"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (sentDatePropertyTree != null) : ((sentDatePropertyTree == null) || (!sentDatePropertyTree.isLeaf())))) {
            _other.sentDate = ((this.sentDate == null) ? null : ((XMLGregorianCalendar) this.sentDate.clone()));
        }
        final PropertyTree fileListPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("fileList"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (fileListPropertyTree != null) : ((fileListPropertyTree == null) || (!fileListPropertyTree.isLeaf())))) {
            _other.fileList = ((this.fileList == null) ? null : this.fileList.newCopyBuilder(_other, fileListPropertyTree, _propertyTreeUse));
        }
        final PropertyTree propertyListPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("propertyList"));
        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (propertyListPropertyTree != null) : ((propertyListPropertyTree == null) || (!propertyListPropertyTree.isLeaf())))) {
            _other.propertyList = ((this.propertyList == null) ? null : this.propertyList.newCopyBuilder(_other, propertyListPropertyTree, _propertyTreeUse));
        }
    }

    public <_B> BrokerServiceManifest.Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return new BrokerServiceManifest.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
    }

    public BrokerServiceManifest.Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
    }

    public static <_B> BrokerServiceManifest.Builder<_B> copyOf(final BrokerServiceManifest _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
        final BrokerServiceManifest.Builder<_B> _newBuilder = new BrokerServiceManifest.Builder<_B>(null, null, false);
        _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
        return _newBuilder;
    }

    public static BrokerServiceManifest.Builder<Void> copyExcept(final BrokerServiceManifest _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
    }

    public static BrokerServiceManifest.Builder<Void> copyOnly(final BrokerServiceManifest _other, final PropertyTree _propertyTree) {
        return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
    }

    public static class Builder<_B> implements Buildable {

        protected final _B _parentBuilder;
        protected final BrokerServiceManifest _storedValue;
        private String externalServiceCode;
        private BigInteger externalServiceEditionCode;
        private String sendersReference;
        private String reportee;
        private XMLGregorianCalendar sentDate;
        private BrokerServiceManifest.FileList.Builder<BrokerServiceManifest.Builder<_B>> fileList;
        private BrokerServiceManifest.PropertyList.Builder<BrokerServiceManifest.Builder<_B>> propertyList;

        public Builder(final _B _parentBuilder, final BrokerServiceManifest _other, final boolean _copy) {
            this._parentBuilder = _parentBuilder;
            if (_other != null) {
                if (_copy) {
                    _storedValue = null;
                    this.externalServiceCode = _other.externalServiceCode;
                    this.externalServiceEditionCode = _other.externalServiceEditionCode;
                    this.sendersReference = _other.sendersReference;
                    this.reportee = _other.reportee;
                    this.sentDate = ((_other.sentDate == null) ? null : ((XMLGregorianCalendar) _other.sentDate.clone()));
                    this.fileList = ((_other.fileList == null) ? null : _other.fileList.newCopyBuilder(this));
                    this.propertyList = ((_other.propertyList == null) ? null : _other.propertyList.newCopyBuilder(this));
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public Builder(final _B _parentBuilder, final BrokerServiceManifest _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            this._parentBuilder = _parentBuilder;
            if (_other != null) {
                if (_copy) {
                    _storedValue = null;
                    final PropertyTree externalServiceCodePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("externalServiceCode"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (externalServiceCodePropertyTree != null) : ((externalServiceCodePropertyTree == null) || (!externalServiceCodePropertyTree.isLeaf())))) {
                        this.externalServiceCode = _other.externalServiceCode;
                    }
                    final PropertyTree externalServiceEditionCodePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("externalServiceEditionCode"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (externalServiceEditionCodePropertyTree != null) : ((externalServiceEditionCodePropertyTree == null) || (!externalServiceEditionCodePropertyTree.isLeaf())))) {
                        this.externalServiceEditionCode = _other.externalServiceEditionCode;
                    }
                    final PropertyTree sendersReferencePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("sendersReference"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (sendersReferencePropertyTree != null) : ((sendersReferencePropertyTree == null) || (!sendersReferencePropertyTree.isLeaf())))) {
                        this.sendersReference = _other.sendersReference;
                    }
                    final PropertyTree reporteePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("reportee"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (reporteePropertyTree != null) : ((reporteePropertyTree == null) || (!reporteePropertyTree.isLeaf())))) {
                        this.reportee = _other.reportee;
                    }
                    final PropertyTree sentDatePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("sentDate"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (sentDatePropertyTree != null) : ((sentDatePropertyTree == null) || (!sentDatePropertyTree.isLeaf())))) {
                        this.sentDate = ((_other.sentDate == null) ? null : ((XMLGregorianCalendar) _other.sentDate.clone()));
                    }
                    final PropertyTree fileListPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("fileList"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (fileListPropertyTree != null) : ((fileListPropertyTree == null) || (!fileListPropertyTree.isLeaf())))) {
                        this.fileList = ((_other.fileList == null) ? null : _other.fileList.newCopyBuilder(this, fileListPropertyTree, _propertyTreeUse));
                    }
                    final PropertyTree propertyListPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("propertyList"));
                    if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (propertyListPropertyTree != null) : ((propertyListPropertyTree == null) || (!propertyListPropertyTree.isLeaf())))) {
                        this.propertyList = ((_other.propertyList == null) ? null : _other.propertyList.newCopyBuilder(this, propertyListPropertyTree, _propertyTreeUse));
                    }
                } else {
                    _storedValue = _other;
                }
            } else {
                _storedValue = null;
            }
        }

        public _B end() {
            return this._parentBuilder;
        }

        protected <_P extends BrokerServiceManifest> _P init(final _P _product) {
            _product.externalServiceCode = this.externalServiceCode;
            _product.externalServiceEditionCode = this.externalServiceEditionCode;
            _product.sendersReference = this.sendersReference;
            _product.reportee = this.reportee;
            _product.sentDate = this.sentDate;
            _product.fileList = ((this.fileList == null) ? null : this.fileList.build());
            _product.propertyList = ((this.propertyList == null) ? null : this.propertyList.build());
            return _product;
        }

        /**
         * Sets the new value of "externalServiceCode" (any previous value will be replaced)
         *
         * @param externalServiceCode New value of the "externalServiceCode" property.
         */
        public BrokerServiceManifest.Builder<_B> withExternalServiceCode(final String externalServiceCode) {
            this.externalServiceCode = externalServiceCode;
            return this;
        }

        /**
         * Sets the new value of "externalServiceEditionCode" (any previous value will be replaced)
         *
         * @param externalServiceEditionCode New value of the "externalServiceEditionCode" property.
         */
        public BrokerServiceManifest.Builder<_B> withExternalServiceEditionCode(final BigInteger externalServiceEditionCode) {
            this.externalServiceEditionCode = externalServiceEditionCode;
            return this;
        }

        /**
         * Sets the new value of "sendersReference" (any previous value will be replaced)
         *
         * @param sendersReference New value of the "sendersReference" property.
         */
        public BrokerServiceManifest.Builder<_B> withSendersReference(final String sendersReference) {
            this.sendersReference = sendersReference;
            return this;
        }

        /**
         * Sets the new value of "reportee" (any previous value will be replaced)
         *
         * @param reportee New value of the "reportee" property.
         */
        public BrokerServiceManifest.Builder<_B> withReportee(final String reportee) {
            this.reportee = reportee;
            return this;
        }

        /**
         * Sets the new value of "sentDate" (any previous value will be replaced)
         *
         * @param sentDate New value of the "sentDate" property.
         */
        public BrokerServiceManifest.Builder<_B> withSentDate(final XMLGregorianCalendar sentDate) {
            this.sentDate = sentDate;
            return this;
        }

        /**
         * Sets the new value of "fileList" (any previous value will be replaced)
         *
         * @param fileList New value of the "fileList" property.
         */
        public BrokerServiceManifest.Builder<_B> withFileList(final BrokerServiceManifest.FileList fileList) {
            this.fileList = ((fileList == null) ? null : new BrokerServiceManifest.FileList.Builder<BrokerServiceManifest.Builder<_B>>(this, fileList, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "fileList" property (replacing previous value).
         * Use {@link BrokerServiceManifest.FileList.Builder#end()} to return to the current builder.
         *
         * @return A new builder to build the value of the "fileList" property.
         * Use {@link BrokerServiceManifest.FileList.Builder#end()} to return to the current builder.
         */
        public BrokerServiceManifest.FileList.Builder<? extends BrokerServiceManifest.Builder<_B>> withFileList() {
            return this.fileList = new BrokerServiceManifest.FileList.Builder<BrokerServiceManifest.Builder<_B>>(this, null, false);
        }

        /**
         * Sets the new value of "propertyList" (any previous value will be replaced)
         *
         * @param propertyList New value of the "propertyList" property.
         */
        public BrokerServiceManifest.Builder<_B> withPropertyList(final BrokerServiceManifest.PropertyList propertyList) {
            this.propertyList = ((propertyList == null) ? null : new BrokerServiceManifest.PropertyList.Builder<BrokerServiceManifest.Builder<_B>>(this, propertyList, false));
            return this;
        }

        /**
         * Returns a new builder to build the value of the "propertyList" property (replacing previous value).
         * Use {@link BrokerServiceManifest.PropertyList.Builder#end()} to return to the current builder.
         *
         * @return A new builder to build the value of the "propertyList" property.
         * Use {@link BrokerServiceManifest.PropertyList.Builder#end()} to return to the current builder.
         */
        public BrokerServiceManifest.PropertyList.Builder<? extends BrokerServiceManifest.Builder<_B>> withPropertyList() {
            return this.propertyList = new BrokerServiceManifest.PropertyList.Builder<BrokerServiceManifest.Builder<_B>>(this, null, false);
        }

        @Override
        public BrokerServiceManifest build() {
            if (_storedValue == null) {
                return this.init(new BrokerServiceManifest());
            } else {
                return ((BrokerServiceManifest) _storedValue);
            }
        }

    }


    /**
     * This property should hold a list of the files included in the shipment. This is optional.
     *
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="File" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="CheckSum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "file"
    })
    public static class FileList {

        @XmlElement(name = "File")
        protected List<BrokerServiceManifest.FileList.File> file;

        /**
         * Gets the value of the file property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the file property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFile().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BrokerServiceManifest.FileList.File }
         *
         *
         */
        public List<BrokerServiceManifest.FileList.File> getFile() {
            if (file == null) {
                file = new ArrayList<BrokerServiceManifest.FileList.File>();
            }
            return this.file;
        }

        /**
         * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
         *
         * @param _other A builder instance to which the state of this object will be copied.
         */
        public <_B> void copyTo(final BrokerServiceManifest.FileList.Builder<_B> _other) {
            if (this.file == null) {
                _other.file = null;
            } else {
                _other.file = new ArrayList<BrokerServiceManifest.FileList.File.Builder<BrokerServiceManifest.FileList.Builder<_B>>>();
                for (BrokerServiceManifest.FileList.File _item : this.file) {
                    _other.file.add(((_item == null) ? null : _item.newCopyBuilder(_other)));
                }
            }
        }

        public <_B> BrokerServiceManifest.FileList.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
            return new BrokerServiceManifest.FileList.Builder<_B>(_parentBuilder, this, true);
        }

        public BrokerServiceManifest.FileList.Builder<Void> newCopyBuilder() {
            return newCopyBuilder(null);
        }

        public static BrokerServiceManifest.FileList.Builder<Void> builder() {
            return new BrokerServiceManifest.FileList.Builder<Void>(null, null, false);
        }

        public static <_B> BrokerServiceManifest.FileList.Builder<_B> copyOf(final BrokerServiceManifest.FileList _other) {
            final BrokerServiceManifest.FileList.Builder<_B> _newBuilder = new BrokerServiceManifest.FileList.Builder<_B>(null, null, false);
            _other.copyTo(_newBuilder);
            return _newBuilder;
        }

        /**
         * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
         *
         * @param _other A builder instance to which the state of this object will be copied.
         */
        public <_B> void copyTo(final BrokerServiceManifest.FileList.Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            final PropertyTree filePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("file"));
            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (filePropertyTree != null) : ((filePropertyTree == null) || (!filePropertyTree.isLeaf())))) {
                if (this.file == null) {
                    _other.file = null;
                } else {
                    _other.file = new ArrayList<BrokerServiceManifest.FileList.File.Builder<BrokerServiceManifest.FileList.Builder<_B>>>();
                    for (BrokerServiceManifest.FileList.File _item : this.file) {
                        _other.file.add(((_item == null) ? null : _item.newCopyBuilder(_other, filePropertyTree, _propertyTreeUse)));
                    }
                }
            }
        }

        public <_B> BrokerServiceManifest.FileList.Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            return new BrokerServiceManifest.FileList.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
        }

        public BrokerServiceManifest.FileList.Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
        }

        public static <_B> BrokerServiceManifest.FileList.Builder<_B> copyOf(final BrokerServiceManifest.FileList _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            final BrokerServiceManifest.FileList.Builder<_B> _newBuilder = new BrokerServiceManifest.FileList.Builder<_B>(null, null, false);
            _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
            return _newBuilder;
        }

        public static BrokerServiceManifest.FileList.Builder<Void> copyExcept(final BrokerServiceManifest.FileList _other, final PropertyTree _propertyTree) {
            return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
        }

        public static BrokerServiceManifest.FileList.Builder<Void> copyOnly(final BrokerServiceManifest.FileList _other, final PropertyTree _propertyTree) {
            return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
        }

        public static class Builder<_B> implements Buildable {

            protected final _B _parentBuilder;
            protected final BrokerServiceManifest.FileList _storedValue;
            private List<BrokerServiceManifest.FileList.File.Builder<BrokerServiceManifest.FileList.Builder<_B>>> file;

            public Builder(final _B _parentBuilder, final BrokerServiceManifest.FileList _other, final boolean _copy) {
                this._parentBuilder = _parentBuilder;
                if (_other != null) {
                    if (_copy) {
                        _storedValue = null;
                        if (_other.file == null) {
                            this.file = null;
                        } else {
                            this.file = new ArrayList<BrokerServiceManifest.FileList.File.Builder<BrokerServiceManifest.FileList.Builder<_B>>>();
                            for (BrokerServiceManifest.FileList.File _item : _other.file) {
                                this.file.add(((_item == null) ? null : _item.newCopyBuilder(this)));
                            }
                        }
                    } else {
                        _storedValue = _other;
                    }
                } else {
                    _storedValue = null;
                }
            }

            public Builder(final _B _parentBuilder, final BrokerServiceManifest.FileList _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                this._parentBuilder = _parentBuilder;
                if (_other != null) {
                    if (_copy) {
                        _storedValue = null;
                        final PropertyTree filePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("file"));
                        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (filePropertyTree != null) : ((filePropertyTree == null) || (!filePropertyTree.isLeaf())))) {
                            if (_other.file == null) {
                                this.file = null;
                            } else {
                                this.file = new ArrayList<BrokerServiceManifest.FileList.File.Builder<BrokerServiceManifest.FileList.Builder<_B>>>();
                                for (BrokerServiceManifest.FileList.File _item : _other.file) {
                                    this.file.add(((_item == null) ? null : _item.newCopyBuilder(this, filePropertyTree, _propertyTreeUse)));
                                }
                            }
                        }
                    } else {
                        _storedValue = _other;
                    }
                } else {
                    _storedValue = null;
                }
            }

            public _B end() {
                return this._parentBuilder;
            }

            protected <_P extends BrokerServiceManifest.FileList> _P init(final _P _product) {
                if (this.file != null) {
                    final List<BrokerServiceManifest.FileList.File> file = new ArrayList<BrokerServiceManifest.FileList.File>(this.file.size());
                    for (BrokerServiceManifest.FileList.File.Builder<BrokerServiceManifest.FileList.Builder<_B>> _item : this.file) {
                        file.add(_item.build());
                    }
                    _product.file = file;
                }
                return _product;
            }

            /**
             * Adds the given items to the value of "file"
             *
             * @param file Items to add to the value of the "file" property
             */
            public BrokerServiceManifest.FileList.Builder<_B> addFile(final Iterable<? extends BrokerServiceManifest.FileList.File> file) {
                if (file != null) {
                    if (this.file == null) {
                        this.file = new ArrayList<BrokerServiceManifest.FileList.File.Builder<BrokerServiceManifest.FileList.Builder<_B>>>();
                    }
                    for (BrokerServiceManifest.FileList.File _item : file) {
                        this.file.add(new BrokerServiceManifest.FileList.File.Builder<BrokerServiceManifest.FileList.Builder<_B>>(this, _item, false));
                    }
                }
                return this;
            }

            /**
             * Sets the new value of "file" (any previous value will be replaced)
             *
             * @param file New value of the "file" property.
             */
            public BrokerServiceManifest.FileList.Builder<_B> withFile(final Iterable<? extends BrokerServiceManifest.FileList.File> file) {
                if (this.file != null) {
                    this.file.clear();
                }
                return addFile(file);
            }

            /**
             * Adds the given items to the value of "file"
             *
             * @param file Items to add to the value of the "file" property
             */
            public BrokerServiceManifest.FileList.Builder<_B> addFile(BrokerServiceManifest.FileList.File... file) {
                addFile(Arrays.asList(file));
                return this;
            }

            /**
             * Sets the new value of "file" (any previous value will be replaced)
             *
             * @param file New value of the "file" property.
             */
            public BrokerServiceManifest.FileList.Builder<_B> withFile(BrokerServiceManifest.FileList.File... file) {
                withFile(Arrays.asList(file));
                return this;
            }

            /**
             * Returns a new builder to build an additional value of the "File" property.
             * Use {@link BrokerServiceManifest.FileList.File.Builder#end()} to return to the current builder.
             *
             * @return a new builder to build an additional value of the "File" property.
             * Use {@link BrokerServiceManifest.FileList.File.Builder#end()} to return to the current builder.
             */
            public BrokerServiceManifest.FileList.File.Builder<? extends BrokerServiceManifest.FileList.Builder<_B>> addFile() {
                if (this.file == null) {
                    this.file = new ArrayList<BrokerServiceManifest.FileList.File.Builder<BrokerServiceManifest.FileList.Builder<_B>>>();
                }
                final BrokerServiceManifest.FileList.File.Builder<BrokerServiceManifest.FileList.Builder<_B>> file_Builder = new BrokerServiceManifest.FileList.File.Builder<BrokerServiceManifest.FileList.Builder<_B>>(this, null, false);
                this.file.add(file_Builder);
                return file_Builder;
            }

            @Override
            public BrokerServiceManifest.FileList build() {
                if (_storedValue == null) {
                    return this.init(new BrokerServiceManifest.FileList());
                } else {
                    return ((BrokerServiceManifest.FileList) _storedValue);
                }
            }

        }


        /**
         * This property should hold information about a file in the package.
         *
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="CheckSum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "fileName",
                "checkSum"
        })
        public static class File {

            @XmlElement(name = "FileName", required = true)
            protected String fileName;
            @XmlElement(name = "CheckSum")
            protected String checkSum;

            /**
             * Gets the value of the fileName property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getFileName() {
                return fileName;
            }

            /**
             * Sets the value of the fileName property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setFileName(String value) {
                this.fileName = value;
            }

            /**
             * Gets the value of the checkSum property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getCheckSum() {
                return checkSum;
            }

            /**
             * Sets the value of the checkSum property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setCheckSum(String value) {
                this.checkSum = value;
            }

            /**
             * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
             *
             * @param _other A builder instance to which the state of this object will be copied.
             */
            public <_B> void copyTo(final BrokerServiceManifest.FileList.File.Builder<_B> _other) {
                _other.fileName = this.fileName;
                _other.checkSum = this.checkSum;
            }

            public <_B> BrokerServiceManifest.FileList.File.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
                return new BrokerServiceManifest.FileList.File.Builder<_B>(_parentBuilder, this, true);
            }

            public BrokerServiceManifest.FileList.File.Builder<Void> newCopyBuilder() {
                return newCopyBuilder(null);
            }

            public static BrokerServiceManifest.FileList.File.Builder<Void> builder() {
                return new BrokerServiceManifest.FileList.File.Builder<Void>(null, null, false);
            }

            public static <_B> BrokerServiceManifest.FileList.File.Builder<_B> copyOf(final BrokerServiceManifest.FileList.File _other) {
                final BrokerServiceManifest.FileList.File.Builder<_B> _newBuilder = new BrokerServiceManifest.FileList.File.Builder<_B>(null, null, false);
                _other.copyTo(_newBuilder);
                return _newBuilder;
            }

            /**
             * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
             *
             * @param _other A builder instance to which the state of this object will be copied.
             */
            public <_B> void copyTo(final BrokerServiceManifest.FileList.File.Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                final PropertyTree fileNamePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("fileName"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (fileNamePropertyTree != null) : ((fileNamePropertyTree == null) || (!fileNamePropertyTree.isLeaf())))) {
                    _other.fileName = this.fileName;
                }
                final PropertyTree checkSumPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("checkSum"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (checkSumPropertyTree != null) : ((checkSumPropertyTree == null) || (!checkSumPropertyTree.isLeaf())))) {
                    _other.checkSum = this.checkSum;
                }
            }

            public <_B> BrokerServiceManifest.FileList.File.Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                return new BrokerServiceManifest.FileList.File.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
            }

            public BrokerServiceManifest.FileList.File.Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
            }

            public static <_B> BrokerServiceManifest.FileList.File.Builder<_B> copyOf(final BrokerServiceManifest.FileList.File _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                final BrokerServiceManifest.FileList.File.Builder<_B> _newBuilder = new BrokerServiceManifest.FileList.File.Builder<_B>(null, null, false);
                _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
                return _newBuilder;
            }

            public static BrokerServiceManifest.FileList.File.Builder<Void> copyExcept(final BrokerServiceManifest.FileList.File _other, final PropertyTree _propertyTree) {
                return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
            }

            public static BrokerServiceManifest.FileList.File.Builder<Void> copyOnly(final BrokerServiceManifest.FileList.File _other, final PropertyTree _propertyTree) {
                return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
            }

            public static class Builder<_B> implements Buildable {

                protected final _B _parentBuilder;
                protected final BrokerServiceManifest.FileList.File _storedValue;
                private String fileName;
                private String checkSum;

                public Builder(final _B _parentBuilder, final BrokerServiceManifest.FileList.File _other, final boolean _copy) {
                    this._parentBuilder = _parentBuilder;
                    if (_other != null) {
                        if (_copy) {
                            _storedValue = null;
                            this.fileName = _other.fileName;
                            this.checkSum = _other.checkSum;
                        } else {
                            _storedValue = _other;
                        }
                    } else {
                        _storedValue = null;
                    }
                }

                public Builder(final _B _parentBuilder, final BrokerServiceManifest.FileList.File _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                    this._parentBuilder = _parentBuilder;
                    if (_other != null) {
                        if (_copy) {
                            _storedValue = null;
                            final PropertyTree fileNamePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("fileName"));
                            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (fileNamePropertyTree != null) : ((fileNamePropertyTree == null) || (!fileNamePropertyTree.isLeaf())))) {
                                this.fileName = _other.fileName;
                            }
                            final PropertyTree checkSumPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("checkSum"));
                            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (checkSumPropertyTree != null) : ((checkSumPropertyTree == null) || (!checkSumPropertyTree.isLeaf())))) {
                                this.checkSum = _other.checkSum;
                            }
                        } else {
                            _storedValue = _other;
                        }
                    } else {
                        _storedValue = null;
                    }
                }

                public _B end() {
                    return this._parentBuilder;
                }

                protected <_P extends BrokerServiceManifest.FileList.File> _P init(final _P _product) {
                    _product.fileName = this.fileName;
                    _product.checkSum = this.checkSum;
                    return _product;
                }

                /**
                 * Sets the new value of "fileName" (any previous value will be replaced)
                 *
                 * @param fileName New value of the "fileName" property.
                 */
                public BrokerServiceManifest.FileList.File.Builder<_B> withFileName(final String fileName) {
                    this.fileName = fileName;
                    return this;
                }

                /**
                 * Sets the new value of "checkSum" (any previous value will be replaced)
                 *
                 * @param checkSum New value of the "checkSum" property.
                 */
                public BrokerServiceManifest.FileList.File.Builder<_B> withCheckSum(final String checkSum) {
                    this.checkSum = checkSum;
                    return this;
                }

                @Override
                public BrokerServiceManifest.FileList.File build() {
                    if (_storedValue == null) {
                        return this.init(new BrokerServiceManifest.FileList.File());
                    } else {
                        return ((BrokerServiceManifest.FileList.File) _storedValue);
                    }
                }

            }

            public static class Select
                    extends BrokerServiceManifest.FileList.File.Selector<BrokerServiceManifest.FileList.File.Select, Void> {


                Select() {
                    super(null, null, null);
                }

                public static BrokerServiceManifest.FileList.File.Select _root() {
                    return new BrokerServiceManifest.FileList.File.Select();
                }

            }

            public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
                    extends com.kscs.util.jaxb.Selector<TRoot, TParent> {

                private com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.FileList.File.Selector<TRoot, TParent>> fileName = null;
                private com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.FileList.File.Selector<TRoot, TParent>> checkSum = null;

                public Selector(final TRoot root, final TParent parent, final String propertyName) {
                    super(root, parent, propertyName);
                }

                @Override
                public Map<String, PropertyTree> buildChildren() {
                    final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
                    products.putAll(super.buildChildren());
                    if (this.fileName != null) {
                        products.put("fileName", this.fileName.init());
                    }
                    if (this.checkSum != null) {
                        products.put("checkSum", this.checkSum.init());
                    }
                    return products;
                }

                public com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.FileList.File.Selector<TRoot, TParent>> fileName() {
                    return ((this.fileName == null) ? this.fileName = new com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.FileList.File.Selector<TRoot, TParent>>(this._root, this, "fileName") : this.fileName);
                }

                public com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.FileList.File.Selector<TRoot, TParent>> checkSum() {
                    return ((this.checkSum == null) ? this.checkSum = new com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.FileList.File.Selector<TRoot, TParent>>(this._root, this, "checkSum") : this.checkSum);
                }

            }

        }

        public static class Select
                extends BrokerServiceManifest.FileList.Selector<BrokerServiceManifest.FileList.Select, Void> {


            Select() {
                super(null, null, null);
            }

            public static BrokerServiceManifest.FileList.Select _root() {
                return new BrokerServiceManifest.FileList.Select();
            }

        }

        public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
                extends com.kscs.util.jaxb.Selector<TRoot, TParent> {

            private BrokerServiceManifest.FileList.File.Selector<TRoot, BrokerServiceManifest.FileList.Selector<TRoot, TParent>> file = null;

            public Selector(final TRoot root, final TParent parent, final String propertyName) {
                super(root, parent, propertyName);
            }

            @Override
            public Map<String, PropertyTree> buildChildren() {
                final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
                products.putAll(super.buildChildren());
                if (this.file != null) {
                    products.put("file", this.file.init());
                }
                return products;
            }

            public BrokerServiceManifest.FileList.File.Selector<TRoot, BrokerServiceManifest.FileList.Selector<TRoot, TParent>> file() {
                return ((this.file == null) ? this.file = new BrokerServiceManifest.FileList.File.Selector<TRoot, BrokerServiceManifest.FileList.Selector<TRoot, TParent>>(this._root, this, "file") : this.file);
            }

        }

    }


    /**
     * This property can hold a list of custom values agreed upon between sender and receivers. This is optional.
     *
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Property" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="PropertyKey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="PropertyValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "property"
    })
    public static class PropertyList {

        @XmlElement(name = "Property")
        protected List<BrokerServiceManifest.PropertyList.Property> property;

        /**
         * Gets the value of the property property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BrokerServiceManifest.PropertyList.Property }
         *
         *
         */
        public List<BrokerServiceManifest.PropertyList.Property> getProperty() {
            if (property == null) {
                property = new ArrayList<BrokerServiceManifest.PropertyList.Property>();
            }
            return this.property;
        }

        /**
         * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
         *
         * @param _other A builder instance to which the state of this object will be copied.
         */
        public <_B> void copyTo(final BrokerServiceManifest.PropertyList.Builder<_B> _other) {
            if (this.property == null) {
                _other.property = null;
            } else {
                _other.property = new ArrayList<BrokerServiceManifest.PropertyList.Property.Builder<BrokerServiceManifest.PropertyList.Builder<_B>>>();
                for (BrokerServiceManifest.PropertyList.Property _item : this.property) {
                    _other.property.add(((_item == null) ? null : _item.newCopyBuilder(_other)));
                }
            }
        }

        public <_B> BrokerServiceManifest.PropertyList.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
            return new BrokerServiceManifest.PropertyList.Builder<_B>(_parentBuilder, this, true);
        }

        public BrokerServiceManifest.PropertyList.Builder<Void> newCopyBuilder() {
            return newCopyBuilder(null);
        }

        public static BrokerServiceManifest.PropertyList.Builder<Void> builder() {
            return new BrokerServiceManifest.PropertyList.Builder<Void>(null, null, false);
        }

        public static <_B> BrokerServiceManifest.PropertyList.Builder<_B> copyOf(final BrokerServiceManifest.PropertyList _other) {
            final BrokerServiceManifest.PropertyList.Builder<_B> _newBuilder = new BrokerServiceManifest.PropertyList.Builder<_B>(null, null, false);
            _other.copyTo(_newBuilder);
            return _newBuilder;
        }

        /**
         * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
         *
         * @param _other A builder instance to which the state of this object will be copied.
         */
        public <_B> void copyTo(final BrokerServiceManifest.PropertyList.Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            final PropertyTree propertyPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("property"));
            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (propertyPropertyTree != null) : ((propertyPropertyTree == null) || (!propertyPropertyTree.isLeaf())))) {
                if (this.property == null) {
                    _other.property = null;
                } else {
                    _other.property = new ArrayList<BrokerServiceManifest.PropertyList.Property.Builder<BrokerServiceManifest.PropertyList.Builder<_B>>>();
                    for (BrokerServiceManifest.PropertyList.Property _item : this.property) {
                        _other.property.add(((_item == null) ? null : _item.newCopyBuilder(_other, propertyPropertyTree, _propertyTreeUse)));
                    }
                }
            }
        }

        public <_B> BrokerServiceManifest.PropertyList.Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            return new BrokerServiceManifest.PropertyList.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
        }

        public BrokerServiceManifest.PropertyList.Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
        }

        public static <_B> BrokerServiceManifest.PropertyList.Builder<_B> copyOf(final BrokerServiceManifest.PropertyList _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
            final BrokerServiceManifest.PropertyList.Builder<_B> _newBuilder = new BrokerServiceManifest.PropertyList.Builder<_B>(null, null, false);
            _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
            return _newBuilder;
        }

        public static BrokerServiceManifest.PropertyList.Builder<Void> copyExcept(final BrokerServiceManifest.PropertyList _other, final PropertyTree _propertyTree) {
            return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
        }

        public static BrokerServiceManifest.PropertyList.Builder<Void> copyOnly(final BrokerServiceManifest.PropertyList _other, final PropertyTree _propertyTree) {
            return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
        }

        public static class Builder<_B> implements Buildable {

            protected final _B _parentBuilder;
            protected final BrokerServiceManifest.PropertyList _storedValue;
            private List<BrokerServiceManifest.PropertyList.Property.Builder<BrokerServiceManifest.PropertyList.Builder<_B>>> property;

            public Builder(final _B _parentBuilder, final BrokerServiceManifest.PropertyList _other, final boolean _copy) {
                this._parentBuilder = _parentBuilder;
                if (_other != null) {
                    if (_copy) {
                        _storedValue = null;
                        if (_other.property == null) {
                            this.property = null;
                        } else {
                            this.property = new ArrayList<BrokerServiceManifest.PropertyList.Property.Builder<BrokerServiceManifest.PropertyList.Builder<_B>>>();
                            for (BrokerServiceManifest.PropertyList.Property _item : _other.property) {
                                this.property.add(((_item == null) ? null : _item.newCopyBuilder(this)));
                            }
                        }
                    } else {
                        _storedValue = _other;
                    }
                } else {
                    _storedValue = null;
                }
            }

            public Builder(final _B _parentBuilder, final BrokerServiceManifest.PropertyList _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                this._parentBuilder = _parentBuilder;
                if (_other != null) {
                    if (_copy) {
                        _storedValue = null;
                        final PropertyTree propertyPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("property"));
                        if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (propertyPropertyTree != null) : ((propertyPropertyTree == null) || (!propertyPropertyTree.isLeaf())))) {
                            if (_other.property == null) {
                                this.property = null;
                            } else {
                                this.property = new ArrayList<BrokerServiceManifest.PropertyList.Property.Builder<BrokerServiceManifest.PropertyList.Builder<_B>>>();
                                for (BrokerServiceManifest.PropertyList.Property _item : _other.property) {
                                    this.property.add(((_item == null) ? null : _item.newCopyBuilder(this, propertyPropertyTree, _propertyTreeUse)));
                                }
                            }
                        }
                    } else {
                        _storedValue = _other;
                    }
                } else {
                    _storedValue = null;
                }
            }

            public _B end() {
                return this._parentBuilder;
            }

            protected <_P extends BrokerServiceManifest.PropertyList> _P init(final _P _product) {
                if (this.property != null) {
                    final List<BrokerServiceManifest.PropertyList.Property> property = new ArrayList<BrokerServiceManifest.PropertyList.Property>(this.property.size());
                    for (BrokerServiceManifest.PropertyList.Property.Builder<BrokerServiceManifest.PropertyList.Builder<_B>> _item : this.property) {
                        property.add(_item.build());
                    }
                    _product.property = property;
                }
                return _product;
            }

            /**
             * Adds the given items to the value of "property"
             *
             * @param property Items to add to the value of the "property" property
             */
            public BrokerServiceManifest.PropertyList.Builder<_B> addProperty(final Iterable<? extends BrokerServiceManifest.PropertyList.Property> property) {
                if (property != null) {
                    if (this.property == null) {
                        this.property = new ArrayList<BrokerServiceManifest.PropertyList.Property.Builder<BrokerServiceManifest.PropertyList.Builder<_B>>>();
                    }
                    for (BrokerServiceManifest.PropertyList.Property _item : property) {
                        this.property.add(new BrokerServiceManifest.PropertyList.Property.Builder<BrokerServiceManifest.PropertyList.Builder<_B>>(this, _item, false));
                    }
                }
                return this;
            }

            /**
             * Sets the new value of "property" (any previous value will be replaced)
             *
             * @param property New value of the "property" property.
             */
            public BrokerServiceManifest.PropertyList.Builder<_B> withProperty(final Iterable<? extends BrokerServiceManifest.PropertyList.Property> property) {
                if (this.property != null) {
                    this.property.clear();
                }
                return addProperty(property);
            }

            /**
             * Adds the given items to the value of "property"
             *
             * @param property Items to add to the value of the "property" property
             */
            public BrokerServiceManifest.PropertyList.Builder<_B> addProperty(BrokerServiceManifest.PropertyList.Property... property) {
                addProperty(Arrays.asList(property));
                return this;
            }

            /**
             * Sets the new value of "property" (any previous value will be replaced)
             *
             * @param property New value of the "property" property.
             */
            public BrokerServiceManifest.PropertyList.Builder<_B> withProperty(BrokerServiceManifest.PropertyList.Property... property) {
                withProperty(Arrays.asList(property));
                return this;
            }

            /**
             * Returns a new builder to build an additional value of the "Property" property.
             * Use {@link BrokerServiceManifest.PropertyList.Property.Builder#end()} to return to the current builder.
             *
             * @return a new builder to build an additional value of the "Property" property.
             * Use {@link BrokerServiceManifest.PropertyList.Property.Builder#end()} to return to the current builder.
             */
            public BrokerServiceManifest.PropertyList.Property.Builder<? extends BrokerServiceManifest.PropertyList.Builder<_B>> addProperty() {
                if (this.property == null) {
                    this.property = new ArrayList<BrokerServiceManifest.PropertyList.Property.Builder<BrokerServiceManifest.PropertyList.Builder<_B>>>();
                }
                final BrokerServiceManifest.PropertyList.Property.Builder<BrokerServiceManifest.PropertyList.Builder<_B>> property_Builder = new BrokerServiceManifest.PropertyList.Property.Builder<BrokerServiceManifest.PropertyList.Builder<_B>>(this, null, false);
                this.property.add(property_Builder);
                return property_Builder;
            }

            @Override
            public BrokerServiceManifest.PropertyList build() {
                if (_storedValue == null) {
                    return this.init(new BrokerServiceManifest.PropertyList());
                } else {
                    return ((BrokerServiceManifest.PropertyList) _storedValue);
                }
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="PropertyKey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="PropertyValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "propertyKey",
                "propertyValue"
        })
        public static class Property {

            @XmlElement(name = "PropertyKey", required = true)
            protected String propertyKey;
            @XmlElement(name = "PropertyValue", required = true)
            protected String propertyValue;

            /**
             * Gets the value of the propertyKey property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getPropertyKey() {
                return propertyKey;
            }

            /**
             * Sets the value of the propertyKey property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setPropertyKey(String value) {
                this.propertyKey = value;
            }

            /**
             * Gets the value of the propertyValue property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getPropertyValue() {
                return propertyValue;
            }

            /**
             * Sets the value of the propertyValue property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setPropertyValue(String value) {
                this.propertyValue = value;
            }

            /**
             * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
             *
             * @param _other A builder instance to which the state of this object will be copied.
             */
            public <_B> void copyTo(final BrokerServiceManifest.PropertyList.Property.Builder<_B> _other) {
                _other.propertyKey = this.propertyKey;
                _other.propertyValue = this.propertyValue;
            }

            public <_B> BrokerServiceManifest.PropertyList.Property.Builder<_B> newCopyBuilder(final _B _parentBuilder) {
                return new BrokerServiceManifest.PropertyList.Property.Builder<_B>(_parentBuilder, this, true);
            }

            public BrokerServiceManifest.PropertyList.Property.Builder<Void> newCopyBuilder() {
                return newCopyBuilder(null);
            }

            public static BrokerServiceManifest.PropertyList.Property.Builder<Void> builder() {
                return new BrokerServiceManifest.PropertyList.Property.Builder<Void>(null, null, false);
            }

            public static <_B> BrokerServiceManifest.PropertyList.Property.Builder<_B> copyOf(final BrokerServiceManifest.PropertyList.Property _other) {
                final BrokerServiceManifest.PropertyList.Property.Builder<_B> _newBuilder = new BrokerServiceManifest.PropertyList.Property.Builder<_B>(null, null, false);
                _other.copyTo(_newBuilder);
                return _newBuilder;
            }

            /**
             * Copies all state of this object to a builder. This method is used by the {@link #copyOf} method and should not be called directly by client code.
             *
             * @param _other A builder instance to which the state of this object will be copied.
             */
            public <_B> void copyTo(final BrokerServiceManifest.PropertyList.Property.Builder<_B> _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                final PropertyTree propertyKeyPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("propertyKey"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (propertyKeyPropertyTree != null) : ((propertyKeyPropertyTree == null) || (!propertyKeyPropertyTree.isLeaf())))) {
                    _other.propertyKey = this.propertyKey;
                }
                final PropertyTree propertyValuePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("propertyValue"));
                if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (propertyValuePropertyTree != null) : ((propertyValuePropertyTree == null) || (!propertyValuePropertyTree.isLeaf())))) {
                    _other.propertyValue = this.propertyValue;
                }
            }

            public <_B> BrokerServiceManifest.PropertyList.Property.Builder<_B> newCopyBuilder(final _B _parentBuilder, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                return new BrokerServiceManifest.PropertyList.Property.Builder<_B>(_parentBuilder, this, true, _propertyTree, _propertyTreeUse);
            }

            public BrokerServiceManifest.PropertyList.Property.Builder<Void> newCopyBuilder(final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                return newCopyBuilder(null, _propertyTree, _propertyTreeUse);
            }

            public static <_B> BrokerServiceManifest.PropertyList.Property.Builder<_B> copyOf(final BrokerServiceManifest.PropertyList.Property _other, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                final BrokerServiceManifest.PropertyList.Property.Builder<_B> _newBuilder = new BrokerServiceManifest.PropertyList.Property.Builder<_B>(null, null, false);
                _other.copyTo(_newBuilder, _propertyTree, _propertyTreeUse);
                return _newBuilder;
            }

            public static BrokerServiceManifest.PropertyList.Property.Builder<Void> copyExcept(final BrokerServiceManifest.PropertyList.Property _other, final PropertyTree _propertyTree) {
                return copyOf(_other, _propertyTree, PropertyTreeUse.EXCLUDE);
            }

            public static BrokerServiceManifest.PropertyList.Property.Builder<Void> copyOnly(final BrokerServiceManifest.PropertyList.Property _other, final PropertyTree _propertyTree) {
                return copyOf(_other, _propertyTree, PropertyTreeUse.INCLUDE);
            }

            public static class Builder<_B> implements Buildable {

                protected final _B _parentBuilder;
                protected final BrokerServiceManifest.PropertyList.Property _storedValue;
                private String propertyKey;
                private String propertyValue;

                public Builder(final _B _parentBuilder, final BrokerServiceManifest.PropertyList.Property _other, final boolean _copy) {
                    this._parentBuilder = _parentBuilder;
                    if (_other != null) {
                        if (_copy) {
                            _storedValue = null;
                            this.propertyKey = _other.propertyKey;
                            this.propertyValue = _other.propertyValue;
                        } else {
                            _storedValue = _other;
                        }
                    } else {
                        _storedValue = null;
                    }
                }

                public Builder(final _B _parentBuilder, final BrokerServiceManifest.PropertyList.Property _other, final boolean _copy, final PropertyTree _propertyTree, final PropertyTreeUse _propertyTreeUse) {
                    this._parentBuilder = _parentBuilder;
                    if (_other != null) {
                        if (_copy) {
                            _storedValue = null;
                            final PropertyTree propertyKeyPropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("propertyKey"));
                            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (propertyKeyPropertyTree != null) : ((propertyKeyPropertyTree == null) || (!propertyKeyPropertyTree.isLeaf())))) {
                                this.propertyKey = _other.propertyKey;
                            }
                            final PropertyTree propertyValuePropertyTree = ((_propertyTree == null) ? null : _propertyTree.get("propertyValue"));
                            if (((_propertyTreeUse == PropertyTreeUse.INCLUDE) ? (propertyValuePropertyTree != null) : ((propertyValuePropertyTree == null) || (!propertyValuePropertyTree.isLeaf())))) {
                                this.propertyValue = _other.propertyValue;
                            }
                        } else {
                            _storedValue = _other;
                        }
                    } else {
                        _storedValue = null;
                    }
                }

                public _B end() {
                    return this._parentBuilder;
                }

                protected <_P extends BrokerServiceManifest.PropertyList.Property> _P init(final _P _product) {
                    _product.propertyKey = this.propertyKey;
                    _product.propertyValue = this.propertyValue;
                    return _product;
                }

                /**
                 * Sets the new value of "propertyKey" (any previous value will be replaced)
                 *
                 * @param propertyKey New value of the "propertyKey" property.
                 */
                public BrokerServiceManifest.PropertyList.Property.Builder<_B> withPropertyKey(final String propertyKey) {
                    this.propertyKey = propertyKey;
                    return this;
                }

                /**
                 * Sets the new value of "propertyValue" (any previous value will be replaced)
                 *
                 * @param propertyValue New value of the "propertyValue" property.
                 */
                public BrokerServiceManifest.PropertyList.Property.Builder<_B> withPropertyValue(final String propertyValue) {
                    this.propertyValue = propertyValue;
                    return this;
                }

                @Override
                public BrokerServiceManifest.PropertyList.Property build() {
                    if (_storedValue == null) {
                        return this.init(new BrokerServiceManifest.PropertyList.Property());
                    } else {
                        return ((BrokerServiceManifest.PropertyList.Property) _storedValue);
                    }
                }

            }

            public static class Select
                    extends BrokerServiceManifest.PropertyList.Property.Selector<BrokerServiceManifest.PropertyList.Property.Select, Void> {


                Select() {
                    super(null, null, null);
                }

                public static BrokerServiceManifest.PropertyList.Property.Select _root() {
                    return new BrokerServiceManifest.PropertyList.Property.Select();
                }

            }

            public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
                    extends com.kscs.util.jaxb.Selector<TRoot, TParent> {

                private com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.PropertyList.Property.Selector<TRoot, TParent>> propertyKey = null;
                private com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.PropertyList.Property.Selector<TRoot, TParent>> propertyValue = null;

                public Selector(final TRoot root, final TParent parent, final String propertyName) {
                    super(root, parent, propertyName);
                }

                @Override
                public Map<String, PropertyTree> buildChildren() {
                    final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
                    products.putAll(super.buildChildren());
                    if (this.propertyKey != null) {
                        products.put("propertyKey", this.propertyKey.init());
                    }
                    if (this.propertyValue != null) {
                        products.put("propertyValue", this.propertyValue.init());
                    }
                    return products;
                }

                public com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.PropertyList.Property.Selector<TRoot, TParent>> propertyKey() {
                    return ((this.propertyKey == null) ? this.propertyKey = new com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.PropertyList.Property.Selector<TRoot, TParent>>(this._root, this, "propertyKey") : this.propertyKey);
                }

                public com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.PropertyList.Property.Selector<TRoot, TParent>> propertyValue() {
                    return ((this.propertyValue == null) ? this.propertyValue = new com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.PropertyList.Property.Selector<TRoot, TParent>>(this._root, this, "propertyValue") : this.propertyValue);
                }

            }

        }

        public static class Select
                extends BrokerServiceManifest.PropertyList.Selector<BrokerServiceManifest.PropertyList.Select, Void> {


            Select() {
                super(null, null, null);
            }

            public static BrokerServiceManifest.PropertyList.Select _root() {
                return new BrokerServiceManifest.PropertyList.Select();
            }

        }

        public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
                extends com.kscs.util.jaxb.Selector<TRoot, TParent> {

            private BrokerServiceManifest.PropertyList.Property.Selector<TRoot, BrokerServiceManifest.PropertyList.Selector<TRoot, TParent>> property = null;

            public Selector(final TRoot root, final TParent parent, final String propertyName) {
                super(root, parent, propertyName);
            }

            @Override
            public Map<String, PropertyTree> buildChildren() {
                final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
                products.putAll(super.buildChildren());
                if (this.property != null) {
                    products.put("property", this.property.init());
                }
                return products;
            }

            public BrokerServiceManifest.PropertyList.Property.Selector<TRoot, BrokerServiceManifest.PropertyList.Selector<TRoot, TParent>> property() {
                return ((this.property == null) ? this.property = new BrokerServiceManifest.PropertyList.Property.Selector<TRoot, BrokerServiceManifest.PropertyList.Selector<TRoot, TParent>>(this._root, this, "property") : this.property);
            }

        }

    }

    public static class Select
            extends BrokerServiceManifest.Selector<BrokerServiceManifest.Select, Void> {


        Select() {
            super(null, null, null);
        }

        public static BrokerServiceManifest.Select _root() {
            return new BrokerServiceManifest.Select();
        }

    }

    public static class Selector<TRoot extends com.kscs.util.jaxb.Selector<TRoot, ?>, TParent>
            extends com.kscs.util.jaxb.Selector<TRoot, TParent> {

        private com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> externalServiceCode = null;
        private com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> externalServiceEditionCode = null;
        private com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> sendersReference = null;
        private com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> reportee = null;
        private com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> sentDate = null;
        private BrokerServiceManifest.FileList.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> fileList = null;
        private BrokerServiceManifest.PropertyList.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> propertyList = null;

        public Selector(final TRoot root, final TParent parent, final String propertyName) {
            super(root, parent, propertyName);
        }

        @Override
        public Map<String, PropertyTree> buildChildren() {
            final Map<String, PropertyTree> products = new HashMap<String, PropertyTree>();
            products.putAll(super.buildChildren());
            if (this.externalServiceCode != null) {
                products.put("externalServiceCode", this.externalServiceCode.init());
            }
            if (this.externalServiceEditionCode != null) {
                products.put("externalServiceEditionCode", this.externalServiceEditionCode.init());
            }
            if (this.sendersReference != null) {
                products.put("sendersReference", this.sendersReference.init());
            }
            if (this.reportee != null) {
                products.put("reportee", this.reportee.init());
            }
            if (this.sentDate != null) {
                products.put("sentDate", this.sentDate.init());
            }
            if (this.fileList != null) {
                products.put("fileList", this.fileList.init());
            }
            if (this.propertyList != null) {
                products.put("propertyList", this.propertyList.init());
            }
            return products;
        }

        public com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> externalServiceCode() {
            return ((this.externalServiceCode == null) ? this.externalServiceCode = new com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>>(this._root, this, "externalServiceCode") : this.externalServiceCode);
        }

        public com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> externalServiceEditionCode() {
            return ((this.externalServiceEditionCode == null) ? this.externalServiceEditionCode = new com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>>(this._root, this, "externalServiceEditionCode") : this.externalServiceEditionCode);
        }

        public com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> sendersReference() {
            return ((this.sendersReference == null) ? this.sendersReference = new com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>>(this._root, this, "sendersReference") : this.sendersReference);
        }

        public com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> reportee() {
            return ((this.reportee == null) ? this.reportee = new com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>>(this._root, this, "reportee") : this.reportee);
        }

        public com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> sentDate() {
            return ((this.sentDate == null) ? this.sentDate = new com.kscs.util.jaxb.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>>(this._root, this, "sentDate") : this.sentDate);
        }

        public BrokerServiceManifest.FileList.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> fileList() {
            return ((this.fileList == null) ? this.fileList = new BrokerServiceManifest.FileList.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>>(this._root, this, "fileList") : this.fileList);
        }

        public BrokerServiceManifest.PropertyList.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>> propertyList() {
            return ((this.propertyList == null) ? this.propertyList = new BrokerServiceManifest.PropertyList.Selector<TRoot, BrokerServiceManifest.Selector<TRoot, TParent>>(this._root, this, "propertyList") : this.propertyList);
        }

    }

}
