//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.12 at 03:14:19 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schema.altinn.no/services/ServiceEngine/Broker/2015/06", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package no.nav.dokdisteformidling.consumer.eformidling.dokumentpakker.brokerservicemanifest;
