//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 12:23:12 PM CET 
//


package no.nav.dokdisteformidling.consumer.eformidling.dokumentpakker.sbdh;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.time.OffsetDateTime;


/**
 * <p>Java class for CorrelationInformation complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CorrelationInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestingDocumentCreationDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="RequestingDocumentInstanceIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExpectedResponseDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CorrelationInformation", propOrder = {
		"requestingDocumentCreationDateTime",
		"requestingDocumentInstanceIdentifier",
		"expectedResponseDateTime"
})
@Getter
@Setter
@ToString
public class CorrelationInformation {

	@XmlElement(name = "RequestingDocumentCreationDateTime")
	@XmlSchemaType(name = "dateTime")
	@XmlJavaTypeAdapter(OffsetDateTimeAdapter.class)
	protected OffsetDateTime requestingDocumentCreationDateTime;

	@XmlElement(name = "RequestingDocumentInstanceIdentifier")
	protected String requestingDocumentInstanceIdentifier;

	@XmlElement(name = "ExpectedResponseDateTime")
	@XmlSchemaType(name = "dateTime")
	@XmlJavaTypeAdapter(OffsetDateTimeAdapter.class)
	@JsonFormat(shape = JsonFormat.Shape.STRING)
	protected OffsetDateTime expectedResponseDateTime;
}
