//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 12:23:12 PM CET 
//


package no.nav.dokdisteformidling.consumer.eformidling.dokumentpakker.sbdh;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import no.nav.dokdisteformidling.consumer.eformidling.Organisasjonsnummer;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlTransient;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import java.io.Serializable;


/**
 * <p>Java class for PartnerIdentification complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PartnerIdentification">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="Authority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnerIdentification", propOrder = {
		"value"
})
@EqualsAndHashCode(exclude = "partner")
@Getter
@Setter
@ToString(exclude = "partner")
@RequiredArgsConstructor
public class PartnerIdentification implements Serializable {

	@XmlTransient
	@JsonIgnore
	private Partner partner;

	@XmlValue
	protected String value;

	@XmlAttribute(name = "Authority")
	protected String authority;

	@JsonIgnore
	String getStrippedValue() {
		if (value == null) {
			return null;
		}

		return Organisasjonsnummer.isIso6523(value) ? Organisasjonsnummer.fromIso6523(value) : value;
	}
}
