//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 12:23:12 PM CET 
//


package no.nav.dokdisteformidling.consumer.eformidling.dokumentpakker.sbdh;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.HashSet;
import java.util.Optional;
import java.util.Set;


/**
 * <p>Java class for StandardBusinessDocumentHeader complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="StandardBusinessDocumentHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HeaderVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sender" type="{http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader}Partner" maxOccurs="unbounded"/>
 *         &lt;element name="Receiver" type="{http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader}Partner" maxOccurs="unbounded"/>
 *         &lt;element name="DocumentIdentification" type="{http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader}DocumentIdentification"/>
 *         &lt;element name="Manifest" type="{http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader}Manifest" minOccurs="0"/>
 *         &lt;element name="BusinessScope" type="{http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader}BusinessScope" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandardBusinessDocumentHeader", propOrder = {
		"headerVersion",
		"sender",
		"receiver",
		"documentIdentification",
		"manifest",
		"businessScope"
})
@Getter
@Setter
@ToString
public class StandardBusinessDocumentHeader {

	@XmlElement(name = "HeaderVersion", required = true)
	private String headerVersion;

	@Setter
	@XmlElement(name = "Sender", required = true)
	private Set<Sender> sender;

	@XmlElement(name = "Receiver", required = true)
	private Set<Receiver> receiver;

	@XmlElement(name = "DocumentIdentification", required = true)
	private DocumentIdentification documentIdentification;

	@XmlElement(name = "Manifest")
	private Manifest manifest;

	@XmlElement(name = "BusinessScope")
	private BusinessScope businessScope;

	public Set<Sender> getSender() {
		if (sender == null) {
			sender = new HashSet<>();
		}
		return this.sender;
	}

	public StandardBusinessDocumentHeader addSender(Sender partner) {
		getSender().add(partner);
		return this;
	}

	public Set<Receiver> getReceiver() {
		if (receiver == null) {
			receiver = new HashSet<>();
		}
		return this.receiver;
	}

	public StandardBusinessDocumentHeader addReceiver(Receiver partner) {
		getReceiver().add(partner);
		return this;
	}

	@JsonIgnore
	Optional<Sender> getFirstSender() {
		if (sender == null) {
			return Optional.empty();
		}
		return sender.stream().findFirst();
	}

	@JsonIgnore
	Optional<Receiver> getFirstReceiver() {
		if (receiver == null) {
			return Optional.empty();
		}
		return receiver.stream().findFirst();
	}

	@JsonIgnore
	public String getReceiverOrganisationNumber() {

		if (receiver.size() != 1) {
			throw new RuntimeException(String.valueOf(receiver.size()));
		}
		Partner partner = receiver.iterator().next();
		PartnerIdentification identifier = partner.getIdentifier();
		if (identifier == null) {
			throw new RuntimeException();
		}
		return identifier.getValue();
	}
}