//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 12:23:12 PM CET 
//


package no.nav.dokdisteformidling.consumer.eformidling.dokumentpakker.sbdh;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import no.nav.dokdisteformidling.consumer.eformidling.dokumentpakker.BusinessMessage;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.Optional;
import java.util.Set;


/**
 * <p>Java class for StandardBusinessDocument complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="StandardBusinessDocument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader}StandardBusinessDocumentHeader" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other'/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandardBusinessDocument", propOrder = {
		"standardBusinessDocumentHeader",
		"any"
})
@Getter
@Setter
@ToString
@JsonSerialize(using = StandardBusinessDocumentSerializer.class)
public class StandardBusinessDocument {

	@XmlElement(name = "StandardBusinessDocumentHeader")
	@NotNull
	@Valid
	private StandardBusinessDocumentHeader standardBusinessDocumentHeader;

	@XmlAnyElement(lax = true)
	@JsonAlias({"arkivmelding", "arkivmelding_kvittering"})
	@NotNull
	private Object any;

	@JsonIgnore
	public BusinessMessage getForretningsmelding() {
		return (BusinessMessage) getAny();
	}

	@JsonIgnore
	public String getSenderIdentifier() {
		return getStandardBusinessDocumentHeader().getFirstSender()
				.map(Partner::getIdentifier)
				.map(PartnerIdentification::getStrippedValue)
				.orElse(null);
	}

	@JsonIgnore
	public String getReceiverIdentifier() {
		return getStandardBusinessDocumentHeader().getFirstReceiver()
				.map(Partner::getIdentifier)
				.map(PartnerIdentification::getStrippedValue)
				.orElse(null);
	}

	@JsonIgnore
	public final String getJournalPostId() {
		return findScope(ScopeType.JOURNALPOST_ID)
				.map(Scope::getInstanceIdentifier)
				.orElse("");
	}

	@JsonIgnore
	public String getConversationId() {
		return getOptionalConversationId()
				.orElseThrow(RuntimeException::new);
	}

	@JsonIgnore
	public Optional<String> getOptionalConversationId() {
		return findScope(ScopeType.CONVERSATION_ID)
				.map(Scope::getInstanceIdentifier);
	}

	@JsonIgnore
	public Set<Scope> getScopes() {
		return getStandardBusinessDocumentHeader()
				.getBusinessScope()
				.getScope();
	}

	public Scope getScope(ScopeType scopeType) {
		return findScope(scopeType)
				.orElseThrow(() -> new RuntimeException(String.format("Missing scope %s", scopeType.name())));
	}

	public Optional<Scope> findScope(ScopeType scopeType) {
		return getScopes()
				.stream()
				.filter(scope -> scopeType.toString().equals(scope.getType()) || scopeType.name().equals(scope.getType()))
				.findAny();
	}

	@JsonIgnore
	public String getMessageType() {
		return getStandardBusinessDocumentHeader().getDocumentIdentification().getType();
	}

	@JsonIgnore
	public String getStandard() {
		return getStandardBusinessDocumentHeader().getDocumentIdentification().getStandard();
	}

	@JsonIgnore
	public String getProcess() {
		return getScope(ScopeType.CONVERSATION_ID)
				.getIdentifier();
	}

	@JsonIgnore
	public String getDocumentId() {
		return getStandardBusinessDocumentHeader().getDocumentIdentification().getInstanceIdentifier();
	}

	@JsonIgnore
	public String getMessageId() {
		return getDocumentId();
	}

	@JsonIgnore
	public Optional<String> getOptionalMessageId() {
		return Optional.ofNullable(getDocumentId());
	}
}
