<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<artifactId>dokdisteformidling</artifactId>
		<groupId>no.nav.dokdisteformidling</groupId>
		<version>1.0-SNAPSHOT</version>
	</parent>

	<artifactId>schemas-avtaltmelding</artifactId>

	<dependencies>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.patrodyne.jvnet</groupId>
				<artifactId>hisrc-higherjaxb-maven-plugin</artifactId>
				<version>${maven-jaxb2-plugin.version}</version>
				<dependencies>
					<dependency>
						<groupId>org.glassfish.jaxb</groupId>
						<artifactId>jaxb-runtime</artifactId>
						<version>${glassfish-jaxb.version}</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>generate-avtaltmelding-v1</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<schemaDirectory>${basedir}/src/main/resources/v1</schemaDirectory>
							<schemaIncludes>
								<include>arkivmeldingNAV.xsd</include>
							</schemaIncludes>
							<bindingDirectory>${basedir}/src/main/resources/v1</bindingDirectory>
							<bindingIncludes>
								<include>bindings.xml</include>
							</bindingIncludes>
							<generateDirectory>${project.build.directory}/generated-sources/avtaltmelding-v1</generateDirectory>
							<strict>true</strict>
							<extension>true</extension>
							<verbose>true</verbose>
							<removeOldOutput>true</removeOldOutput>
							<args>
								<arg>-XfluentAPI</arg>
								<arg>-Xannotate</arg>
								<arg>-Xsimplify</arg>
							</args>
							<plugins>
								<plugin>
									<groupId>org.patrodyne.jvnet</groupId>
									<artifactId>hisrc-hyperjaxb-annox-plugin</artifactId>
									<version>${hisrc-basicjaxb.version}</version>
								</plugin>
								<plugin>
									<groupId>org.patrodyne.jvnet</groupId>
									<artifactId>hisrc-basicjaxb-plugins</artifactId>
									<version>${hisrc-basicjaxb.version}</version>
								</plugin>
								<plugin>
									<groupId>org.patrodyne.jvnet</groupId>
									<artifactId>hisrc-basicjaxb-tools</artifactId>
									<version>${hisrc-basicjaxb.version}</version>
								</plugin>
							</plugins>
						</configuration>
					</execution>
					<execution>
						<id>generate-avtaltmelding-v2</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<schemaDirectory>${basedir}/src/main/resources/v2</schemaDirectory>
							<schemaIncludes>
								<include>avtaltmelding_nav_trygderetten_2.0.xsd</include>
								<include>nav_virksomhet_metadata_1.0.xsd</include>
							</schemaIncludes>
							<bindingDirectory>${basedir}/src/main/resources/v2</bindingDirectory>
							<bindingIncludes>
								<include>bindings.xml</include>
							</bindingIncludes>
							<generateDirectory>${project.build.directory}/generated-sources/avtaltmelding-v2</generateDirectory>
							<strict>true</strict>
							<extension>true</extension>
							<verbose>true</verbose>
							<removeOldOutput>true</removeOldOutput>
							<args>
								<arg>-XfluentAPI</arg>
								<arg>-Xannotate</arg>
								<arg>-Xsimplify</arg>
							</args>
							<plugins>
								<plugin>
									<groupId>org.patrodyne.jvnet</groupId>
									<artifactId>hisrc-hyperjaxb-annox-plugin</artifactId>
									<version>${hisrc-basicjaxb.version}</version>
								</plugin>
								<plugin>
									<groupId>org.patrodyne.jvnet</groupId>
									<artifactId>hisrc-basicjaxb-plugins</artifactId>
									<version>${hisrc-basicjaxb.version}</version>
								</plugin>
								<plugin>
									<groupId>org.patrodyne.jvnet</groupId>
									<artifactId>hisrc-basicjaxb-tools</artifactId>
									<version>${hisrc-basicjaxb.version}</version>
								</plugin>
							</plugins>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>