logging.config=classpath:logback-spring.xml
spring.main.banner_mode=off
# server
server.shutdown=graceful
# actuators
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
management.metrics.enable.http.client.requests=false

altinn.brokerserviceexternal.readtimeoutms=30000
altinn.brokerserviceexternal.connecttimeoutms=5000

# 10 min
altinn.brokerserviceexternalstreamed.readtimeoutms=600000
altinn.brokerserviceexternalstreamed.connecttimeoutms=5000
