logging.config=classpath:logback-spring.xml
spring.main.banner_mode=off
# actuators
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus
management.metrics.enable.http.client.requests=false

server.tomcat.min-spare-threads=50
server.tomcat.max-threads=100

virksomhet.digitalkontakinformasjon.v1.readtimeoutms=15000
virksomhet.digitalkontakinformasjon.v1.connecttimeoutms=3000
storage_s3_url=http://objectstore.rook-ceph.svc.nais.local


altinn.brokerserviceexternal.readtimeoutms=15000
altinn.brokerserviceexternal.connecttimeoutms=3000

altinn.brokerserviceexternalstreamed.readtimeoutms=1500
altinn.brokerserviceexternalstreamed.connecttimeoutms=3000

srvappserver.username=srvappserver
srvappserver.password=

sftp.port=22
sftp.remoteFilePath=dokumentdistribusjon/documentFileshare

feature.usealtinnformidlingstjenesten=false