//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.12 at 03:14:19 PM CET 
//


package no.nav.dokdisteformidling.consumer.eformidling.dokumentpakker.trygderetten.xml;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the no.altinn.schema.services.serviceengine.broker._2015._06 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.altinn.schema.services.serviceengine.broker._2015._06
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BrokerServiceManifest }
     */
    public BrokerServiceManifest createBrokerServiceManifest() {
        return new BrokerServiceManifest();
    }

    /**
     * Create an instance of {@link BrokerServiceManifest.PropertyList }
     */
    public BrokerServiceManifest.PropertyList createBrokerServiceManifestPropertyList() {
        return new BrokerServiceManifest.PropertyList();
    }

    /**
     * Create an instance of {@link BrokerServiceManifest.FileList }
     */
    public BrokerServiceManifest.FileList createBrokerServiceManifestFileList() {
        return new BrokerServiceManifest.FileList();
    }

    /**
     * Create an instance of {@link BrokerServiceManifest.PropertyList.Property }
     */
    public BrokerServiceManifest.PropertyList.Property createBrokerServiceManifestPropertyListProperty() {
        return new BrokerServiceManifest.PropertyList.Property();
    }

    /**
     * Create an instance of {@link BrokerServiceManifest.FileList.File }
     */
    public BrokerServiceManifest.FileList.File createBrokerServiceManifestFileListFile() {
        return new BrokerServiceManifest.FileList.File();
    }

}
