<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:tns="http://www.altinn.no/services/ServiceEngine/Broker/2015/06"
                  xmlns:wsa10="http://www.w3.org/2005/08/addressing"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:xmime="http://www.w3.org/2005/05/xmlmime" name="BrokerServiceExternalStreamedSF"
                  targetNamespace="http://www.altinn.no/services/ServiceEngine/Broker/2015/06">
    <wsp:Policy wsu:Id="CustomBinding_IBrokerServiceExternalStreamed_policy">
    </wsp:Policy>
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.altinn.no/services/2009/10"
                   elementFormDefault="qualified" targetNamespace="http://www.altinn.no/services/2009/10">
            <xs:element name="Test">
                <xs:complexType>
                    <xs:sequence/>
                </xs:complexType>
            </xs:element>
            <xs:element name="TestResponse">
                <xs:complexType>
                    <xs:sequence/>
                </xs:complexType>
            </xs:element>
        </xs:schema>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:element name="anyType" nillable="true" type="xs:anyType"/>
            <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
            <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
            <xs:element name="boolean" nillable="true" type="xs:boolean"/>
            <xs:element name="byte" nillable="true" type="xs:byte"/>
            <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
            <xs:element name="decimal" nillable="true" type="xs:decimal"/>
            <xs:element name="double" nillable="true" type="xs:double"/>
            <xs:element name="float" nillable="true" type="xs:float"/>
            <xs:element name="int" nillable="true" type="xs:int"/>
            <xs:element name="long" nillable="true" type="xs:long"/>
            <xs:element name="QName" nillable="true" type="xs:QName"/>
            <xs:element name="short" nillable="true" type="xs:short"/>
            <xs:element name="string" nillable="true" type="xs:string"/>
            <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
            <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
            <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
            <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
            <xs:element name="char" nillable="true" type="tns:char"/>
            <xs:simpleType name="char">
                <xs:restriction base="xs:int"/>
            </xs:simpleType>
            <xs:element name="duration" nillable="true" type="tns:duration"/>
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid" nillable="true" type="tns:guid"/>
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType" type="xs:QName"/>
            <xs:attribute name="Id" type="xs:ID"/>
            <xs:attribute name="Ref" type="xs:IDREF"/>
        </xs:schema>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.altinn.no/services/common/fault/2009/10" elementFormDefault="qualified" targetNamespace="http://www.altinn.no/services/common/fault/2009/10">
            <xs:complexType name="AltinnFault">
                <xs:annotation>
                    <xs:appinfo/>
                    <xs:documentation>
                        <summary> Represents a SOAP fault message used by Altinn to convey exception information to the caller. </summary>
                    </xs:documentation>
                </xs:annotation>
                <xs:sequence>
                    <xs:element minOccurs="0" name="AltinnErrorMessage" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary> Gets or sets the error message. </summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="AltinnExtendedErrorMessage" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary> Gets or sets the verbose version of the error message. </summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="AltinnLocalizedErrorMessage" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary> Gets or sets the localized version of the error message. </summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="ErrorGuid" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary> Gets or sets the unique GUID for the specific fault. </summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="ErrorID" type="xs:int">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary> Gets or sets the error type id. </summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="UserGuid" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary> Gets or sets the GUID of the user. </summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" name="UserId" nillable="true" type="xs:string">
                        <xs:annotation>
                            <xs:appinfo/>
                            <xs:documentation>
                                <summary> Gets or sets the id of the user. </summary>
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="AltinnFault" nillable="true" type="tns:AltinnFault"/>
        </xs:schema>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/Message" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/Message">
            <xs:simpleType name="StreamBody">
                <xs:restriction base="xs:base64Binary"/>
            </xs:simpleType>
        </xs:schema>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.altinn.no/services/ServiceEngine/Broker/2015/06">
            <xs:import namespace="http://schemas.microsoft.com/Message"/>
            <xs:element name="StreamedPayloadExternalBE">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q1="http://schemas.microsoft.com/Message" name="DataStream" type="q1:StreamBody" xmime:expectedContentTypes="application/octet-stream"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="FileName" nillable="true" type="xs:string"/>
            <xs:element name="Reference" nillable="true" type="xs:string"/>
            <xs:element name="Reportee" nillable="true" type="xs:string"/>
            <xs:element name="ReceiptExternalStreamedBE">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="LastChanged" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="ParentReceiptId" type="xs:int"/>
                        <xs:element minOccurs="0" name="ReceiptHistory" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="ReceiptId" type="xs:int"/>
                        <xs:element minOccurs="0" name="ReceiptStatusCode" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="ReceiptText" nillable="true" type="xs:string"/>
                        <xs:element minOccurs="0" name="ReceiptTypeName" nillable="true" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DownloadFileStreamed">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="1" name="fileReference" type="xs:string"/>
                        <xs:element minOccurs="1" name="reportee" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="DownloadFileStreamedResponse">
                <xs:complexType>
                    <xs:sequence>
                        <!--                        <xs:element xmlns:q2="http://schemas.microsoft.com/Message" name="DownloadFileStreamedResult" type="q2:StreamBody" xmime:expectedContentTypes="application/octet-stream"/>-->
                        <xs:element xmlns:xs="http://www.w3.org/2001/XMLSchema" name="DownloadFileStreamedResult"
                                    type="xs:base64Binary"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="IBrokerServiceExternalStreamed_Test_InputMessage">
        <wsdl:part xmlns:q1="http://www.altinn.no/services/2009/10" name="parameters" element="q1:Test"/>
    </wsdl:message>
    <wsdl:message name="IBrokerServiceExternalStreamed_Test_OutputMessage">
        <wsdl:part xmlns:q2="http://www.altinn.no/services/2009/10" name="parameters" element="q2:TestResponse"/>
    </wsdl:message>
    <wsdl:message name="IBrokerServiceExternalStreamed_Test_AltinnFaultFault_FaultMessage">
        <wsdl:part xmlns:q3="http://www.altinn.no/services/common/fault/2009/10" name="detail" element="q3:AltinnFault"/>
    </wsdl:message>
    <wsdl:message name="StreamedPayloadExternalBE">
        <wsdl:part name="parameters" element="tns:StreamedPayloadExternalBE"/>
    </wsdl:message>
    <wsdl:message name="StreamedPayloadExternalBE_Headers">
        <wsdl:part name="FileName" element="tns:FileName"/>
        <wsdl:part name="Reference" element="tns:Reference"/>
        <wsdl:part name="Reportee" element="tns:Reportee"/>
    </wsdl:message>
    <wsdl:message name="ReceiptExternalStreamedBE">
        <wsdl:part name="parameters" element="tns:ReceiptExternalStreamedBE"/>
    </wsdl:message>
    <wsdl:message name="IBrokerServiceExternalStreamed_UploadFileStreamed_AltinnFaultFault_FaultMessage">
        <wsdl:part xmlns:q4="http://www.altinn.no/services/common/fault/2009/10" name="detail" element="q4:AltinnFault"/>
    </wsdl:message>
    <wsdl:message name="IBrokerServiceExternalStreamed_DownloadFileStreamed_InputMessage">
        <wsdl:part name="parameters" element="tns:DownloadFileStreamed"/>
    </wsdl:message>
    <wsdl:message name="IBrokerServiceExternalStreamed_DownloadFileStreamed_OutputMessage">
        <wsdl:part name="parameters" element="tns:DownloadFileStreamedResponse"/>
    </wsdl:message>
    <wsdl:message name="IBrokerServiceExternalStreamed_DownloadFileStreamed_AltinnFaultFault_FaultMessage">
        <wsdl:part xmlns:q5="http://www.altinn.no/services/common/fault/2009/10" name="detail" element="q5:AltinnFault"/>
    </wsdl:message>
    <wsdl:portType name="IBrokerServiceExternalStreamed">
        <wsdl:documentation>
            <summary> External interface for exposing service operations for Broker Service on WS binding. Used for end user systems to handle file operations. </summary>
        </wsdl:documentation>
        <wsdl:operation name="Test">
            <wsdl:input wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test" message="tns:IBrokerServiceExternalStreamed_Test_InputMessage"/>
            <wsdl:output wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse" message="tns:IBrokerServiceExternalStreamed_Test_OutputMessage"/>
            <wsdl:fault wsaw:Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault" name="AltinnFaultFault" message="tns:IBrokerServiceExternalStreamed_Test_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="UploadFileStreamed">
            <wsdl:documentation>
                <summary> Operation for uploading a file to a broker service. </summary> <param name="payload"> contains stream and authentication information Will contain all the data for submitting a Broker Service Payload to Altinn from the EndUserSystem </param> <returns> The main ReceiptBE entity for the initiated broker service </returns>
            </wsdl:documentation>
            <wsdl:input wsaw:Action="http://www.altinn.no/services/ServiceEngine/Broker/2015/06/IBrokerServiceExternalStreamed/UploadFileStreamed" name="StreamedPayloadExternalBE" message="tns:StreamedPayloadExternalBE"/>
            <wsdl:output wsaw:Action="http://www.altinn.no/services/ServiceEngine/Broker/2015/06/IBrokerServiceExternalStreamed/UploadFileStreamedResponse" name="ReceiptExternalStreamedBE" message="tns:ReceiptExternalStreamedBE"/>
            <wsdl:fault wsaw:Action="http://www.altinn.no/services/ServiceEngine/Broker/2015/06/IBrokerServiceExternalStreamed/UploadFileStreamedAltinnFaultFault" name="AltinnFaultFault" message="tns:IBrokerServiceExternalStreamed_UploadFileStreamed_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
        <wsdl:operation name="DownloadFileStreamed">
            <wsdl:documentation>
                <summary> Operation for downloading a file from a broker service. </summary> <param name="fileReference"> The file reference value of the file that should be downloaded. </param> <param name="reportee"> The social security number or organization number of the reportee. </param> <returns> A stream with the content of the file. </returns>
            </wsdl:documentation>
            <wsdl:input wsaw:Action="http://www.altinn.no/services/ServiceEngine/Broker/2015/06/IBrokerServiceExternalStreamed/DownloadFileStreamed" message="tns:IBrokerServiceExternalStreamed_DownloadFileStreamed_InputMessage"/>
            <wsdl:output wsaw:Action="http://www.altinn.no/services/ServiceEngine/Broker/2015/06/IBrokerServiceExternalStreamed/DownloadFileStreamedResponse" message="tns:IBrokerServiceExternalStreamed_DownloadFileStreamed_OutputMessage"/>
            <wsdl:fault wsaw:Action="http://www.altinn.no/services/ServiceEngine/Broker/2015/06/IBrokerServiceExternalStreamed/DownloadFileStreamedAltinnFaultFault" name="AltinnFaultFault" message="tns:IBrokerServiceExternalStreamed_DownloadFileStreamed_AltinnFaultFault_FaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CustomBinding_IBrokerServiceExternalStreamed" type="tns:IBrokerServiceExternalStreamed">
        <wsp:PolicyReference URI="#CustomBinding_IBrokerServiceExternalStreamed_policy"/>
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Test">
            <soap12:operation soapAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap12:fault use="literal" name="AltinnFaultFault" namespace=""/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="UploadFileStreamed">
            <soap12:operation soapAction="http://www.altinn.no/services/ServiceEngine/Broker/2015/06/IBrokerServiceExternalStreamed/UploadFileStreamed" style="document"/>
            <wsdl:input name="StreamedPayloadExternalBE">
                <soap12:header message="tns:StreamedPayloadExternalBE_Headers" part="FileName" use="literal"/>
                <soap12:header message="tns:StreamedPayloadExternalBE_Headers" part="Reference" use="literal"/>
                <soap12:header message="tns:StreamedPayloadExternalBE_Headers" part="Reportee" use="literal"/>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="ReceiptExternalStreamedBE">
                <soap12:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap12:fault use="literal" name="AltinnFaultFault" namespace=""/>
            </wsdl:fault>
        </wsdl:operation>
        <wsdl:operation name="DownloadFileStreamed">
            <soap12:operation soapAction="http://www.altinn.no/services/ServiceEngine/Broker/2015/06/IBrokerServiceExternalStreamed/DownloadFileStreamed" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="AltinnFaultFault">
                <soap12:fault use="literal" name="AltinnFaultFault" namespace=""/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="BrokerServiceExternalStreamedSF">
        <wsdl:port name="CustomBinding_IBrokerServiceExternalStreamed" binding="tns:CustomBinding_IBrokerServiceExternalStreamed">
            <soap12:address location="https://www.altinn.no/ServiceEngineExternal/BrokerServiceExternalStreamed.svc"/>
            <wsa10:EndpointReference>
                <wsa10:Address>
                    https://www.altinn.no/ServiceEngineExternal/BrokerServiceExternalStreamed.svc
                </wsa10:Address>
            </wsa10:EndpointReference>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>