kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: {{ NAMESPACE }}
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: ADMINISTRERFORSENDELSE_V1_URL
      value: {{ ADMINISTRERFORSENDELSE_V1_URL }}
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: {{ SECURITY_TOKEN_SERVICE_TOKEN_URL }}
    - name: MQGATEWAY01_CHANNEL_NAME
      value: {{ MQGATEWAY01_CHANNEL_NAME }}
    - name: MQGATEWAY01_CHANNEL_SECURENAME
      value: {{ MQGATEWAY01_CHANNEL_SECURENAME }}
    - name: MQGATEWAY01_CHANNEL_ENABLETLS
      value: "{{ MQGATEWAY01_CHANNEL_ENABLETLS }}"
    - name: MQGATEWAY01_NAME
      value: {{ MQGATEWAY01_NAME }}
    - name: MQGATEWAY01_HOSTNAME
      value: {{ MQGATEWAY01_HOSTNAME }}
    - name: MQGATEWAY01_PORT
      value: "{{ MQGATEWAY01_PORT }}"
    - name: DOKDISTEFORMIDLING_QDIST013_DIST_TRYGDERETTEN_QUEUENAME
      value: {{ DOKDISTEFORMIDLING_QDIST013_DIST_TRYGDERETTEN_QUEUENAME }}
    - name: DOKDISTEFORMIDLING_QDIST013_FUNK_FEIL_QUEUENAME
      value: {{ DOKDISTEFORMIDLING_QDIST013_FUNK_FEIL_QUEUENAME }}
    - name: EREG_API_URL
      value: {{ EREG_API_URL }}
    - name: LAGREJURIDISKLOGG_REST_URL
      value: {{ LAGREJURIDISKLOGG_REST_URL }}
    - name: PDL_URL
      value: {{ PDL_URL }}
    - name: SAF_GRAPHQL_URL
      value: {{ SAF_GRAPHQL_URL }}
    - name: MASKINPORTEN_URL
      value: {{ MASKINPORTEN_URL }}
    - name: MASKINPORTEN_AUDIENCE
      value: {{ MASKINPORTEN_AUDIENCE }}
    - name: SERVICEREGISTRY_URL
      value: {{ SERVICEREGISTRY_URL }}
    - name: ALTINN_BROKERSERVICEEXTERNAL_ENDPOINTURL
      value: {{ ALTINN_BROKERSERVICEEXTERNAL_ENDPOINTURL }}
    - name: ALTINN_BROKERSERVICEEXTERNALSTREAMED_ENDPOINTURL
      value: {{ ALTINN_BROKERSERVICEEXTERNALSTREAMED_ENDPOINTURL }}
    - name: DOKDISTMELLOMLAGER_PROJECTID
      value: {{ DOKDISTMELLOMLAGER_PROJECTID }}
    - name: DOKDISTMELLOMLAGER_BUCKET
      value: {{ DOKDISTMELLOMLAGER_BUCKET }}
    - name: DOKDISTMELLOMLAGER_KEYRING
      value: {{ DOKDISTMELLOMLAGER_KEYRING }}
    - name: DOKDISTMELLOMLAGER_KEYID
      value: {{ DOKDISTMELLOMLAGER_KEYID }}
  image: {{ image }}
  ingresses:
    - {{ INGRESSES }}
  leaderElection: true
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 8192Mi
    requests:
      cpu: 60m
      memory: 6144Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVDOKDISTEFORMIDLING }}
        mountPath: "/secrets/serviceuser/srvdokdisteformidling"
      - kvPath: {{ DOKDISTEFORMIDLING_VAULT }}
        mountPath: "/var/run/secrets/nais.io/vault"
      - kvPath: {{ KLAGEINSTANS_VAULT }}
        mountPath: "/secrets/virksomhetssertifikat"
      - kvPath: {{ DOKDISTEFORMIDLING_CERT }}
        mountPath: /var/run/secrets/nais.io/certificate
  webproxy: true
