kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APP_NAME }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: DOKDISTEFORMIDLING_ENDPOINTS_DOKDISTADMIN_URL
      value: {{ DOKDISTEFORMIDLING_ENDPOINTS_DOKDISTADMIN_URL }}
    - name: DOKDISTEFORMIDLING_ENDPOINTS_DOKDISTADMIN_SCOPE
      value: {{ DOKDISTEFORMIDLING_ENDPOINTS_DOKDISTADMIN_SCOPE }}
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: {{ SECURITY_TOKEN_SERVICE_TOKEN_URL }}
    - name: MQGATEWAY01_CHANNEL_SECURENAME
      value: {{ MQGATEWAY01_CHANNEL_SECURENAME }}
    - name: MQGATEWAY01_NAME
      value: {{ MQGATEWAY01_NAME }}
    - name: MQGATEWAY01_HOSTNAME
      value: {{ MQGATEWAY01_HOSTNAME }}
    - name: MQGATEWAY01_PORT
      value: "{{ MQGATEWAY01_PORT }}"
    - name: DOKDISTEFORMIDLING_QDIST013_DIST_TRYGDERETTEN_QUEUENAME
      value: {{ DOKDISTEFORMIDLING_QDIST013_DIST_TRYGDERETTEN_QUEUENAME }}
    - name: DOKDISTEFORMIDLING_QDIST013_FUNK_FEIL_QUEUENAME
      value: {{ DOKDISTEFORMIDLING_QDIST013_FUNK_FEIL_QUEUENAME }}
    - name: DOKDISTEFORMIDLING_ENDPOINTS_EREG_URL
      value: {{ DOKDISTEFORMIDLING_ENDPOINTS_EREG_URL }}
    - name: LAGREJURIDISKLOGG_REST_URL
      value: {{ LAGREJURIDISKLOGG_REST_URL }}
    - name: DOKDISTEFORMIDLING_ENDPOINTS_PDL_URL
      value: {{ DOKDISTEFORMIDLING_ENDPOINTS_PDL_URL }}
    - name: DOKDISTEFORMIDLING_ENDPOINTS_PDL_SCOPE
      value: {{ DOKDISTEFORMIDLING_ENDPOINTS_PDL_SCOPE }}
    - name: SAF_GRAPHQL_URL
      value: {{ SAF_GRAPHQL_URL }}
    - name: MASKINPORTEN_URL
      value: {{ MASKINPORTEN_URL }}
    - name: MASKINPORTEN_AUDIENCE
      value: {{ MASKINPORTEN_AUDIENCE }}
    - name: SERVICEREGISTRY_URL
      value: {{ SERVICEREGISTRY_URL }}
    - name: ALTINN_BROKERSERVICEEXTERNAL_ENDPOINTURL
      value: {{ ALTINN_BROKERSERVICEEXTERNAL_ENDPOINTURL }}
    - name: ALTINN_BROKERSERVICEEXTERNALSTREAMED_ENDPOINTURL
      value: {{ ALTINN_BROKERSERVICEEXTERNALSTREAMED_ENDPOINTURL }}
    - name: KLAGEINSTANS_VIRKSOMHETSSERTIFIKAT_KEY
      value: {{ KLAGEINSTANS_VIRKSOMHETSSERTIFIKAT_KEY }}
    - name: KLAGEINSTANS_VIRKSOMHETSSERTIFIKAT_CREDENTIALS
      value: {{ KLAGEINSTANS_VIRKSOMHETSSERTIFIKAT_CREDENTIALS }}
    - name: DOKDISTMELLOMLAGER_PROJECTID
      value: {{ DOKDISTMELLOMLAGER_PROJECTID }}
    - name: DOKDISTMELLOMLAGER_BUCKET
      value: {{ DOKDISTMELLOMLAGER_BUCKET }}
    - name: DOKDISTMELLOMLAGER_KEYRING
      value: {{ DOKDISTMELLOMLAGER_KEYRING }}
    - name: DOKDISTMELLOMLAGER_KEYID
      value: {{ DOKDISTMELLOMLAGER_KEYID }}
  image: {{ image }}
  ingresses:
    - {{ INGRESSES }}
  leaderElection: true
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: {{ MIN_REPLICAS }}
    max: {{ MAX_REPLICAS }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: {{ MEMORY_LIMITS }}
    requests:
      cpu: 60m
      memory: {{ MEMORY_REQUESTS }}
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVDOKDISTEFORMIDLING }}
        mountPath: "/secrets/serviceuser/srvdokdisteformidling"
      - kvPath: {{ DOKDISTEFORMIDLING_VAULT }}
        mountPath: "/var/run/secrets/nais.io/vault"
      - kvPath: {{ KLAGEINSTANS_VAULT }}
        mountPath: "/secrets/virksomhetssertifikat"
  azure:
    application:
      enabled: true
  webproxy: true
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system