kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: dokdisteformidling
  namespace: default
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: NAV_TRUSTSTORE_KEYSTOREALIAS
      value: na
    - name: SERVICEUSER_USERNAME
      value: srvdokdisteformidl
    - name: SFTP_PRIVATEKEY_KEYSTOREALIAS
      value: na
    - name: SFTP_URL
      value: d26fsvl002.test.local
    - name: SFTP_USERNAME
      value: dokdisteformidling-sftp
    - name: DOKDISTEFORMIDLING_S3_CREDS_USERNAME
      value: VGFWE6C66LF34ME6NRII
    - name: DOKDISTMELLOMLAGER_S3_STORAGE_CRYPTO_USERNAME
      value: whatever
    - name: DOKUMENTTYPEINFO_V4_URL
      value: https://app-t8.adeo.no/dokkat/rest/dokumenttypeinfo/v4
    - name: VARSELINFO_V1_URL
      value: https://app-t8.adeo.no/dokkat/rest/varselinfo/v1
    - name: VARSELINFO_V1_DESCRIPTION
      value: Informasjon om varseltyper og varselmaler
    - name: ADMINISTRERFORSENDELSE_V1_DESCRIPTION
      value: Rest-endepunkt for rdist001 - administrerForsendelse. Endepunktet er sikret
        med basic auth
    - name: ADMINISTRERFORSENDELSE_V1_URL
      value: https://app-t8.adeo.no/dokdist/rest/v1/administrerforsendelse
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-t8.test.local/SecurityTokenServiceProvider/
    - name: SECURITY_TOKEN_SERVICE_TOKEN_URL
      value: https://security-token-service-t4.nais.preprod.local/rest/v1/sts/token
    - name: DOKDISTEFORMIDLING_CHANNEL_QUEUEMANAGER
      value: mq://d26apvl257.test.local:1412/MTXLSC01
    - name: DOKDISTEFORMIDLING_CHANNEL_NAME
      value: T8_DOKDISTEFORMIDLIN
    - name: MQGATEWAY01_NAME
      value: MTXLSC01
    - name: MQGATEWAY01_HOSTNAME
      value: d26apvl257.test.local
    - name: MQGATEWAY01_PORT
      value: "1412"
    - name: DOKDISTEFORMIDLING_QDIST011_DIST_TIL_DPI_QUEUENAME
      value: QA.T8_DOKDISTEFORMIDLING.QDIST011_DIST_TIL_DPI
    - name: DOKDISTEFORMIDLING_QDIST011_DIST_TIL_DPI_QUEUEMANAGER
      value: mq://d26apvl257.test.local:1412/MTXLSC01
    - name: DOKDISTEFORMIDLING_QDIST011_FUNK_FEIL_QUEUENAME
      value: QA.T8_DOKDISTEFORMIDLING.QDIST011_FUNK_FEIL
    - name: DOKDISTEFORMIDLING_QDIST011_FUNK_FEIL_QUEUEMANAGER
      value: mq://d26apvl257.test.local:1412/MTXLSC01
    - name: DOKDISTEFORMIDLING_QDIST013_DIST_TRYGDERETTEN_QUEUEMANAGER
      value: mq://d26apvl257.test.local:1412/MTXLSC01
    - name: DOKDISTEFORMIDLING_QDIST013_DIST_TRYGDERETTEN_QUEUENAME
      value: QA.T8_DOKDISTEFORMIDLING.QDIST013_DIST_TRYGDERE
    - name: DOKDISTEFORMIDLING_QDIST013_FUNK_FEIL_QUEUENAME
      value: QA.T8_DOKDISTEFORMIDLING.QDIST013_FUNK_FEIL
    - name: DOKDISTEFORMIDLING_QDIST013_FUNK_FEIL_QUEUEMANAGER
      value: mq://d26apvl257.test.local:1412/MTXLSC01
    - name: DOKDISTSDPBATCHINTERN_QUEUENAME
      value: T8_475.DOKDIST_SDP_BATCH_INTERN
    - name: VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_WSDLURL
      value: http://maven.adeo.no/nexus/service/local/artifact/maven/redirect?a=nav-digitalKontaktinformasjon-v1-tjenestespesifikasjon&e=zip&g=no.nav.tjenester.fim&r=m2internal&v=2.0.0
    - name: VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_SECURITYTOKEN
      value: SAML
    - name: VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_ENDPOINTURL
      value: https://dkif-t2.nais.preprod.local/ws/DigitalKontaktinformasjon/v1
    - name: VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_DESCRIPTION
      value: Temporary resource, pending update of dokdisteformidling to use dkif rest
        api
    - name: AKTOERREGISTER_API_V1_DESCRIPTION
      value: Versjon 1 av REST-API for aktoerregisteret
    - name: AKTOERREGISTER_API_V1_URL
      value: https://app-t8.adeo.no/aktoerregister/api/v1
    - name: EREG_API_DESCRIPTION
      value: 'REST-API''et for EREG. Dokumentasjon av grensesnittet: se /ereg/api/swagger-ui.html'
    - name: EREG_API_URL
      value: https://modapp-t8.adeo.no/ereg/api
  image: repo.adeo.no:5443/dok/dokdisteformidling
  ingresses:
    - https://dokdisteformidling.nais.preprod.local
  leaderElection: true
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 6
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 3000m
      memory: 2560Mi
    requests:
      cpu: 60m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/test/srvdokdisteformidling
        mountPath: /var/run/secrets/nais.io/srvdokdisteformidling
      - kvPath: /kv/preprod/fss/dokdisteformidling/default
        mountPath: /var/run/secrets/nais.io/vault